### ISSUE TITLE
ProfileInformationController status set to 'profile-information-updated'

### ISSUE THREAD

**Issue by thewebartisan7** [laravel/fortify#100]
After succesfully update of profile information the status is set to 'profile-information-updated'

This string is not even possible to translate.

In my case I have in my main layout something like:

```
        @if (session('status'))
            {{ session('status') }}
        @endif
``` 

And can't even translate that string because the status can be already translated or have different namespace of translation.

Can we add a translated string there? Override that controller for just change that string seem not worth.

In Jetstream you seem just return a generic "Save" message from Livewire, but non-livewire and non-ajax submission need a way to display message from server.

Same thing for update password and two factors. Return 'password-updated' and 'two-factor-authentication-enabled'

Thanks

**Comment by driesvints** [comment]
If you want to change anything here feel free to send in a PR. Thanks

**Comment by thewebartisan7** [comment]
Done. English is not my mother tongue, so I would not be the right person to write these messages. I hope they go well.
