### ISSUE TITLE
Make it so only logged in users can register new users

### ISSUE THREAD

**Issue by Barsnes** [laravel/fortify#111]
It would be nice if it was possible to make it so only logged in users can register new account, prefferably with only one line of code

**Comment by jmpagella** [comment]
If I understand well what you want to do is that there is already a user record and login, then it will be able to create others. If so, you can use the following:

`
$otherUser = (New CreateNewUser)->create(
    $request->only(['name', 'email', 'password', 'password_confirmation'])
);
`

And maybe you want to disable registration feature in config/fortify.php

**Comment by driesvints** [comment]
This logic probably belongs in user land and not natively in Fortify.
