### ISSUE TITLE
Configurable routes

### ISSUE THREAD

**Issue by codebros-nl** [laravel/fortify#117]
Hi,

I totally love the default options we've with Laravel Fortify, however it would be nice to be able to change the registered routes uris. Currently you're stuck with the default naming convention which is based on the English language. 

In my opinion it would be fantastic to have a configurable option within `config/fortify.php`. Lets say something like this:
```
'routes' => [
    'login' => 'inloggen',
    'register' => 'registreer',
    ...
],
```

My current workout is to not use any registered routes, and create the routes myself in the `routes/web.php` file of the Laravel project itself.

**Comment by driesvints** [comment]
Add `Fortify::ignoreRoutes();` in your service provider and register them manually.

**Comment by codebros-nl** [comment]
@driesvints I already found that work around. I am only suggesting an easier way of editing the default routes logic.

**Comment by driesvints** [comment]
@codebros-nl we already rejected prs and issues for that in the past sorry.
