### ISSUE TITLE
Unbundle Features::registration() into Features::registration() and Features::login()

### ISSUE THREAD

**Issue by lofye** [laravel/fortify#121]
Right now you can't disable registration without also disabling login.
I'd like to disable new registrations, but want existing users to be able to continue to login.

**Current config/fortify.php**
`Features::registration(),`

**Suggested config/fortify.php**
`Features::registration(), Features::login(),`

**Comment by driesvints** [comment]
Yeah I think that makes sense. But probably for a new major release unless you can make it backwards compatible. Feel free to PR.
