### ISSUE TITLE
Allow use of custom guards specified in config/auth.php to build multi auth system.

### ISSUE THREAD

**Issue by amit-dalal** [laravel/fortify#126]
In lot of projects we do have multiple user tables based on requirement, so, it is not feasible to have single user table in this scenario. Result is multiple tables in database storing credentials for different roles.

In this case till now we used to specify custom guard in config/auth.php in Laravel for each credential table and use them to build multi-auth system. However, Jetstream is using single guard specified in Fortify.php.

Request: Please provide option to choose guard specified in config/auth.php to create a multiauth system instead of using single guard from fortify.php. At present, we are forced to use only one guard specified in fortify.php to use in application. Please help !!

**Comment by redidizzy** [comment]
Any news regarding that ?

**Comment by driesvints** [comment]
@redidizzy if there hasn't been an update here then no there isn't any news. Anyone's free to send in a PR.

**Comment by amit-dalal** [comment]
@driesvints Please take up this feature on priority as this is one of the main requirement which we feel missing in Laravel.

**Comment by taylorotwell** [comment]
This is a feature request, not a bug.

**Comment by taylorotwell** [comment]
To build your own custom, multi-auth system: https://laravel.com/docs/8.x/authentication#authenticating-users

**Comment by koudera1** [comment]
`class FortifyServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Fortify::createUsersUsing(CreateNewUser::class);
        Fortify::updateUserProfileInformationUsing(UpdateUserProfileInformation::class);
        Fortify::updateUserPasswordsUsing(UpdateUserPassword::class);
        Fortify::resetUserPasswordsUsing(ResetUserPassword::class);
        Fortify::authenticateUsing(function (Request $request) {
            $admin = Admin::where('email', $request->email)
                ->first();
            if ($admin != null and Hash::check($request->password, $admin->password))
            {
                config(['auth.guards.web.provider' => 'admins']);
                return $admin;
            }
            $customer = Customer::where('email', $request->email)
                ->first();
            if ($customer != null and Hash::check($request->password, $customer->password))
            {
                config(['auth.guards.web.provider' => 'customers']);
                return $customer;
            }
        });
    }
}`

**Comment by koudera1** [comment]
`
class FortifyServiceProvider extends ServiceProvider
{

    public function register()
    {
        
    }

    public function boot()
    {
        Fortify::createUsersUsing(CreateNewUser::class);
        Fortify::updateUserProfileInformationUsing(UpdateUserProfileInformation::class);
        Fortify::updateUserPasswordsUsing(UpdateUserPassword::class);
        Fortify::resetUserPasswordsUsing(ResetUserPassword::class);
        Fortify::authenticateUsing(function (Request $request) {
            $admin = Admin::where('email', $request->email)
                ->first();
            if ($admin != null and Hash::check($request->password, $admin->password))
            {
                config(['auth.guards.web.provider' => 'admins']);
                return $admin;
            }
            $customer = Customer::where('email', $request->email)
                ->first();
            if ($customer != null and Hash::check($request->password, $customer->password))
            {
                config(['auth.guards.web.provider' => 'customers']);
                return $customer;
            }
        });
    }
}
`
