### ISSUE TITLE
Trying to install Fortify. Getting an error when trying to publish Fortify's resources

### ISSUE THREAD

**Issue by rotaercz** [laravel/fortify#138]
Did a new project via:

    composer create-project laravel/laravel

Was just following instructions here:

    https://github.com/laravel/fortify

When I run:

    php artisan vendor:publish --provider="Laravel\Fortify\FortifyServiceProvider"

I get the error:

    Unable to locate publishable resources.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
