### ISSUE TITLE
Unsupported api guard

### ISSUE THREAD

**Issue by gaelreyrol** [laravel/fortify#141]
- Fortify Version: 1.7.0
- Laravel Version: 8.14.0
- PHP Version: 7.4
- Database Driver & Version: PostgreSQL

### Description:

If I configure Fortify guard to `api`, it throws an error when requesting any controller using a guard property. The `api` guard is a `TokenGuard` and every controller needs a `StatefulGuard`.

Is Fortify not supposed to be used with `api` guard ?

Regards

**Comment by taylorotwell** [comment]
No, it's not supposed to be used with that guard.

**Comment by driesvints** [comment]
I've sent in a PR to the docs to clarify this: https://github.com/laravel/fortify/pull/146
