### ISSUE TITLE
Illuminate\Auth\Events\Failed not being triggered

### ISSUE THREAD

**Issue by nckrtl** [laravel/fortify#145]
- Fortify Version: 1.7.0
- Laravel Version: 8.14.0
- PHP Version: 7.4.11
- Database Driver & Version: MySQL 8.0

### Description:
It seems that Illuminate\Auth\Events\Failed is not being triggered upon a failed login attempt. Other auth events are working fine as far as I can tell.

### Steps To Reproduce:
1. Setup Laravel with jetstream 
2. Add auth event listeners as described here: https://laravel.com/docs/8.x/authentication
3. Add a dd() in the handle method of the listeners that's bound to Illuminate\Auth\Events\Failed
4. Login with faulty credentials
5. The dd() in the listener won't be triggered.

This issue is also being described here: https://stackoverflow.com/questions/64666382/laravel-8-auth-attempting-and-failed-events-not-firing-as-expected

The reason I made this bug report in the fortify repository is because I'm also having this issue without Jetstream and just Fortify. That's why I think it's perhaps Fortify related.

I'm not sure how to further debug to get to the root of the problem, any help would be appreciated.

Edit:
After some digging around I noticed that the default order of Fortify::authenticateThrough is:

```
        Fortify::authenticateThrough(function (Request $request) {
            return array_filter([
                    config('fortify.limiters.login') ? null : EnsureLoginIsNotThrottled::class,
                    RedirectIfTwoFactorAuthenticatable::class,
                    AttemptToAuthenticate::class,
                    PrepareAuthenticatedSession::class,
            ]);
        });
```

Should AttemptToAuthenticate::class not come before RedirectIfTwoFactorAuthenticatable::class? Like:

```
        Fortify::authenticateThrough(function (Request $request) {
            return array_filter([
                    config('fortify.limiters.login') ? null : EnsureLoginIsNotThrottled::class,
                    AttemptToAuthenticate::class,
                    RedirectIfTwoFactorAuthenticatable::class,
                    PrepareAuthenticatedSession::class,
            ]);
        });
```

By making this change in the FortifyServiceProvider the events fire as expected. Not sure if this might have any unintended side effects.

**Comment by driesvints** [comment]
> After some digging around I noticed that the default order of Fortify::authenticateThrough is:

Where do you see this? I can't find this anywhere.

**Comment by nckrtl** [comment]
https://github.com/laravel/fortify/blob/1.x/src/Http/Controllers/AuthenticatedSessionController.php

**Comment by driesvints** [comment]
Switching those two is something we cannot do as the `AttemptToAuthenticate` will actually attempt to login the user. The event not firing does seems like a genuine concern though.

**Comment by nckrtl** [comment]
I could set up a repo so it can be verified, if that would help.

**Comment by driesvints** [comment]
No, we verified it ourselves. Just trying to figure out what the best solution could be.

**Comment by driesvints** [comment]
Fixed in next release thanks to @rodrigopedra

**Comment by dhi2** [comment]
I realize this was closed 5 years ago, and I see the `Failed` event was resolved, but the `Attempting` event is still not being triggered. For now I am triggering it manually inside `Fortify::authenticateThrough` as a workaround.
