### ISSUE TITLE
The provided two factor authentication code was invalid.

### ISSUE THREAD

**Issue by akhzarjaved** [laravel/fortify#149]
- Fortify Version: 1.6.2
- Laravel Version: 8.12.3
- PHP Version: 7.4.10
- Database Driver & Version: 8.0.13 - MySQL
 
### Description:
I have used laravel fortify without jetstream.
The 2FA is always returning false.

Recovery codes are working but the 6 digit code always return false

```php
class TwoFactorAuthenticatedSessionController extends Controller
{
  
  	... 
    
	/**
     * Attempt to authenticate a new session using the two factor authentication code.
     *
     * @param  \Laravel\Fortify\Http\Requests\TwoFactorLoginRequest  $request
     * @return mixed
     */
    public function store(TwoFactorLoginRequest $request)
    {
        $user = $request->challengedUser();

        if ($code = $request->validRecoveryCode()) {
            $user->replaceRecoveryCode($code);
        } elseif (! $request->hasValidCode()) {  // This always return false
            return app(FailedTwoFactorLoginResponse::class);
        }

        $this->guard->login($user, $request->remember());

        return app(TwoFactorLoginResponse::class);
    }
  
}
```

### $request->hasValidCode()

```php
public function hasValidCode()
    {
        return $this->code && app(TwoFactorAuthenticationProvider::class)->verify(
            decrypt($this->challengedUser()->two_factor_secret), $this->code
        );
    }
```

I haven't changed the fortify backend. I have only converted the frontend to bootstrap (Without jetstream).

### Steps To Reproduce:
There is no steps to be honest, I have activated the 2FA for a account and it provided the barcode with recovery codes.
I logged out from the account & tried to login.
The 6 digit code never worked. Only recovery code works.
I am using **Google Authenticator**

**Comment by akhzarjaved** [comment]
I just tried with a fresh laravel installation with jetstream.
It didn't work on fresh project as well.
Am i missing something ?

**Comment by driesvints** [comment]
Works fine for me on a fresh Jetstream install.
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by driesvints** [comment]
Works fine for me on a fresh jetstream install. Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
