### ISSUE TITLE
Enabling 2FA should require a valid auth code

### ISSUE THREAD

**Issue by jcoby** [laravel/fortify#151]
- Fortify Version: 1.7.1

### Description:

The default jetstream/fortify app does not require a valid 2fa code to enable 2fa. This can/will lead to issues where someone enables 2fa but doesn't have the QR code saved. At next login the user will be locked out.

### Steps To Reproduce:

1. Go to Profile
2. Two Factor Authentication section, click Enable
3. Log out
4. Attempt to log in, 2fa code is required but you don't have it. The account is effectively unusable without NULLing out the 2fa columns in the users record.

**Comment by driesvints** [comment]
https://github.com/laravel/fortify/issues/139
https://github.com/laravel/fortify/issues/47

**Comment by mpbarlow** [comment]
Just in case anyone stumbles on this thread in search of an answer (as I did), it's fairly simple to implement this yourself (with the caveat that you may need to update your database schema once it gets added to Fortify itself).

Add a boolean column on your `User` model to track whether the user as confirmed 2FA; e.g. `two_factor_confirmed`.

Next, in your `FortifyServiceProvider`, you can take advantage of the fact that the view registration callbacks allow you to return any sort of response, not just views:

```php
Fortify::twoFactorChallengeView(function (Request $request) {
    // Fortify stores the user ID in the session before redirecting to the 2FA challenge, so no user
    // is actually logged in at this point (and so $request->user() is null).
    $user = User::find($request->session()->get('login.id'));

    if (! $user) {
        return redirect()
            ->route('login')
            ->withErrors(['email' => __('auth.failed')]);
    }

    if (! $user->two_factor_confirmed) {
        app(DisableTwoFactorAuthentication::class)($user);

        return redirect()
            ->route('login')
            ->withErrors(__('auth.2fa_not_completed'));
    }

    return view('auth.two-factor-challenge');
});
```

Here, you can fetch the user you are about to do a 2FA challenge for, and check for the flag. If it's not set, you can disable 2FA for the user, and redirect them elsewhere. `DisableTwoFactorAuthentication` is an action class that ships with Fortify, and is what its own controllers use.

I guess you could technically log the user in at this point and redirect them to your app, but I feel it's safer to redirect them back to the login and let the framework/Fortify handle a fresh login. My `2fa_not_completed` error message just informs the user that they did not complete the 2FA setup process, so it has been disabled, and to please log in again.

The final step is just to adjust your 2FA setup screen. When you display the QR code to the user, prompt them to enter a code, and if the code is valid, set the flag. Check [`TwoFactorLoginRequest`](https://github.com/laravel/fortify/blob/1.x/src/Http/Requests/TwoFactorLoginRequest.php#L55) if you're not sure how to check the code is valid yourself.
