### ISSUE TITLE
Specifying Additional Conditions

### ISSUE THREAD

**Issue by vwasteels** [laravel/fortify#153]
Is there a way to add condition for the login like an `active` boolean ?

I am refering to something like this : 
https://laravel.com/docs/8.x/authentication#specifying-additional-conditions

thanks a lot

**Comment by Tarzis** [comment]
You can use the `Fortify::authenticateUsing()` method for this.

Documentation: https://github.com/laravel/fortify#customizing-user-authentication

**Comment by vwasteels** [comment]
Thanks !!
