### ISSUE TITLE
Open auth up to support any method

### ISSUE THREAD

**Issue by viezel** [laravel/fortify#16]
Im looking into adding Single Sign On support in Fortify. If we had the ability to add extra steps in the pipeline shown in the below code from `Laravel\Fortify\Http\Controllers\AuthenticatedSessionController`, then its extensible to add SSO or other auth methods into the mix.

```php
public function store(LoginRequest $request)
{
    return (new Pipeline(app()))->send($request)->through(array_filter([
        config('fortify.limiters.login') ? null : EnsureLoginIsNotThrottled::class,
        RedirectIfTwoFactorAuthenticatable::class,
        AttemptToAuthenticate::class,
        PrepareAuthenticatedSession::class,
    ]))->then(function ($request) {
        return app(LoginResponse::class);
    });
}
```

agree?

**Comment by taylorotwell** [comment]
Fortify 1.1.0 has been released with `Laravel\Fortify\Fortify::loginThrough` method... this method should return the authentication pipeline array you wish to use - allowing full customization:

```php
Fortify::loginThrough(function ($request) {
    return [
        //
    ];
});
```
