### ISSUE TITLE
`Fortify::authenticateUsing` custom verification

### ISSUE THREAD

**Issue by bangbangda** [laravel/fortify#160]
There is a verification code in the login page. How to verify that it required and whether it is correct? 
Rules show demo:
```
'validCode' => 'required|captcha'
```

**Comment by bangbangda** [comment]
Is this a good way?

Add code in config\fortify.php file:
```
'rules' => [
    'login' => [
        'validCode' => 'required|captcha'
    ]
],
```

Update code in Laravel\Fortify\Http\Requests\LoginRequest.php 
```
public function rules()
{
    return array_merge([
        Fortify::username() => 'required|string',
        'password' => 'required|string',
    ], config('fortify.rules.login'));
}
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by phpmac** [comment]
hello, i need change username and password ,They are not necessary.

username and password is nullable,i want to add new column,Please give me advice.

**Comment by phpmac** [comment]
hello
