### ISSUE TITLE
Constructor dependency injector avoids Laravel Fortify to work out of the box in Tenancy for Laravel package

### ISSUE THREAD

**Issue by acacha** [laravel/fortify#163]
According to: 

https://tenancyforlaravel.com/docs/v3/early-identification

Using constructor DI avoids tenancy route middleware to works. AFAIK the proposed changes like using method injection instead of constructor will solve the issue.

I can write a Pull Request if your think the change is viable. Feel free to close this issue for any reason.

**Comment by driesvints** [comment]
If you want to change anything just PR it, thanks

**Comment by acacha** [comment]
PR created at https://github.com/laravel/fortify/pull/165

**Comment by acacha** [comment]
PR created at https://github.com/laravel/fortify/pull/169  . Sorry for the multiple PR with errors.
