### ISSUE TITLE
[v1.0] Extensibility of Actions using Authentication User Providers

### ISSUE THREAD

**Issue by stevebauman** [laravel/fortify#17]
I know this is extremely early since this *just* got released -- but I'm wondering if there's any plans on adding the ability to override the included actions, or for the actions to utilize other authentication providers besides `eloquent`?

The current `RedirectIfTwoFactorAuthenticatable` action uses a `getModel()` method that is not currently inside the `Stateful` guard contract:

https://github.com/laravel/fortify/blob/f29ed3f63d6da006fb540e2894e4aa387ccabde2/src/Actions/RedirectIfTwoFactorAuthenticatable.php#L51

This action (`RedirectIfTwoFactorAuthenticatable`) is also responsible for validating the users credentials -- but isn't the authentication `UserProvider` responsible for this?

https://github.com/laravel/framework/blob/c87794fc354941729d1f0c4607693c0b8d2cfda2/src/Illuminate/Contracts/Auth/UserProvider.php#L48

The other concern is that the `AttemptToAuthenticate` action only allows customization of the username passed into the `$guard->attempt()` method, while Laravel UI allows you to customize the whole array of credentials passed in:

**AttemptToAuthenticate Action in Fortify**:
https://github.com/laravel/fortify/blob/4be99538e23fc4a04a4cbf305ab055f2e52537b6/src/Actions/AttemptToAuthenticate.php#L46-L53

**AuthenticatesUsers Trait in Laravel UI**:
https://github.com/laravel/ui/blob/6ed3b97576fc99049ba576de4cfab5cef4771ab3/auth-backend/AuthenticatesUsers.php#L93-L96

Please don't take these questions in any sort of negative manor -- I'm immensely grateful for the insane amount of free work that was put into this! ❤️ 

If there is interest in this possibility, I can work on a PR to add this extensibility and you can look at it to see if it's something you like / don't like. If it's denied, no hard feelings 👍 

Related: #16, https://github.com/DirectoryTree/LdapRecord-Laravel/issues/196

**Comment by taylorotwell** [comment]
Fortify 1.1.0 has been released with `Laravel\Fortify\Fortify::loginThrough` method... this method should return the authentication pipeline array you wish to use - allowing full customization. Could add this to the `boot` method of your `JetstreamServiceProvider`:

```php
Fortify::loginThrough(function ($request) {
    return [
        //
    ];
});
```

**Comment by stevebauman** [comment]
Awesome thanks @taylorotwell! Let me verify this right now on my install and see if I can now use my own auth guard 👍

**Comment by taylorotwell** [comment]
This is sort of the "bazooka" approach and gives the most flexibility. I think there is probably still room for some more granular customization hooks that don't require customizing the pipeline.

**Comment by taylorotwell** [comment]
OK I have tagged v1.2.0 with a more granular approach that I believe will solve your original use case. The `loginThrough` method I noted earlier still works though if you prefer a wider customization.

There is a new `authenticateUsing(fn)` method which receives the request and should retrieve the authenticatable user (however you want) using the data from the request and return the user instance or, if there is not a user matching those credentials, you should return `null` or `false`. Note that you are responsible for validating the password, etc.

This custom callback will be utilized by both `RedirectIfTwoFactorAuthenticatable` and `AttemptToAuthenticate`.

```php
Fortify::authenticateUsing(function ($request) {
    $user = User::where('email', $request->email)->first();

    if (! $user) {
        return;
    }

    if (! Hash::check($request->password, $user->password)) {
        return;
    }

    return $user;
});
```

**Comment by taylorotwell** [comment]
@stevebauman when you have time, i would be curious to know if the new `authenticateUsing` method noted above solves your use case.

**Comment by stevebauman** [comment]
Perfect, the `Fortify::authenticateUsing` callback is exactly what I need. Here's how I'm now able to login using my own [authentication provider](https://github.com/DirectoryTree/LdapRecord-Laravel/blob/master/src/Auth/DatabaseUserProvider.php):

```php
// app/Providers/AppServiceProvider.php

public function boot()
{
    Fortify::authenticateUsing(function ($request) {
        Auth::attempt([
            // "mail" is an LDAP attribute
            'mail' => $request->email,
            'password' => $request->password
        ]);

        return Auth::user();
    });
}
```

This is the **only** change I need to make. I didn't need to configure anything at all in Jetstream. I did a complete new Jetstream installation, installed LdapRecord-Laravel, configured it, then added this callback.

Excellent! 👍

**Comment by taylorotwell** [comment]
@stevebauman cool. my only suggestion is not to use `Auth::attempt` there. I would maybe use `Auth::validate` instead, which accepts the same arguments.

Reason being is that when `authenticateUsing` return a user instance then Fortify will call `Auth::login` for you. So you're sort of logging in twice here.

**Comment by stevebauman** [comment]
@taylorotwell Ah okay understood - thanks! Here's what I've updated it to:

```php
// app/Providers/AppServiceProvider.php

public function boot()
{
    Fortify::authenticateUsing(function ($request) {
        $validated = Auth::validate($credentials = [
            'mail' => $request->email,
            'password' => $request->password
        ]);

        return $validated ? Auth::getProvider()->retrieveByCredentials($credentials) : null;
    });
}
```

In my case, I need to all `retrieveByCredentials()` on the provider to retrieve the user instance from LDAP directory.

**Comment by taylorotwell** [comment]
Yeah, that looks good!

**Comment by ninjaparade** [comment]
![image](https://user-images.githubusercontent.com/228899/92804478-37b7d200-f36d-11ea-93ab-812fd5ebc60e.png)

**Comment by mikeburton220** [comment]
> Yeah, that looks good!

Hi Taylor, is there a way to utilize "remember" using Auth::validate with authenticateUsing, maybe it can be updated to return an array, instead of just the User model? [User, $remember]

**Comment by stevebauman** [comment]
Hi @mikeburton220,

The filled status of the login requests `remember` field will still be passed into the `guard->login()` method, as shown here:

https://github.com/laravel/fortify/blob/394c70778126630a76bb956bd29aeab9cb4e9f66/src/Actions/AttemptToAuthenticate.php#L77

Simply send the `remember` input value with the login request, and you're good to go 👍

**Comment by fahmiegerton** [comment]
> OK I have tagged v1.2.0 with a more granular approach that I believe will solve your original use case a little easier. The `loginThrough` method I noted earlier still works though if you prefer a wider customization.
> 
> There is a new `authenticateUsing(fn)` method which receives the request and should retrieve the authenticatable user (however you want) using the data from the request and return the user instance or, if there is not a user matching those credentials, you should return `null` or `false`. Note that you are responsible for validating the password, etc.
> 
> This custom callback will be utilized by both `RedirectIfTwoFactorAuthenticatable` and `AttemptToAuthenticate`.
> 
> ```
> Fortify::authenticateUsing(function ($request) {
>     $user = User::where('email', $request->email)->first();
> 
>     if (! $user || ! Hash::check($request->password, $user->password)) {
>         return;
>     }
> 
>     return $user;
> });
> ```

I still got this problem, I just want to add additional `where()` but got
![image](https://user-images.githubusercontent.com/5303871/151935327-4acc445a-74aa-491b-8ebd-9fcd828360cb.png)

if I didn't checked the remember me box, it will be fine, otherwise it doesn't work :(.

**Comment by ToneZen** [comment]
@stevebauman  @mikeburton220 
'remember' doesn't work at all after adding 'remember: true' to the login request parameter

This is my JS login request code
`            await axios.get('/sanctum/csrf-cookie').then( () => {
                // Login...
                axios.post('/api/login', {email, password, remember: true} ).then(response => {
                    if (response.data) {
                        console.log('Success'); 
                        console.log(response.data)
                        window.open(redirectToAfterLogin_url, '_self');

                        // states.setAuth({
                        //     ...states.auth,
                        //     logged: true
                        // })
                    }
                }).catch((err) => {
                    // console.log('err ==========', err);
                    // console.log('err.response.data ==========', err.response.data);
                    setError(err.response.data.errors[Object.keys(err.response.data.errors)[0]]);
                })
    
            });`
