### ISSUE TITLE
Documentation: Add `two_factor_secret`, `two_factor_recovery_codes`, to `User::$hidden`

### ISSUE THREAD

**Issue by LeoniePhiline** [laravel/fortify#170]
- Fortify Version: 1.7.2
- Laravel Version: 8.19.0

### Description:
Hi there!

While reading through the Fortify code and documentation, I found no automagic measure (e.g. in the TwoFactorAuthenticatable trait) and no hint in the documentation to add `'two_factor_secret'` and `'two_factor_recovery_codes'` to the `User` model's `$hidden` property.

Since damage can be avoided, I makes sense instructing users accordingly or auto-hiding these attributes.

**Comment by driesvints** [comment]
Feel free to send a PR to the docs.
