### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by buismaarten** [laravel/fortify#19]
Will Laravel Fortify gets a documentation website in the near future?

This will be very convenient to write our own implementations of an authentication system.

**Comment by driesvints** [comment]
Probably not as we mainly intent fortify to be used with Jetstream. Those docs can be found here: https://jetstream.laravel.com/1.x/introduction.html

**Comment by ConsoleTVs** [comment]
@driesvints I am curious for a couple of things:

For example, my intention is normally to use laravel as an API service. I normally don't work with any front-end stuff. That said, I am currently using sanctrum for SPA authentication for a next.js app. Is there a way to use Fortify / Jetstream with 0 front-end on the laravel side? The old "delete the files you don't use" is not my cup of tea for a back-end framework. What if people don't want front-end stuff to be placed in the first place? Is this something possible?
