### ISSUE TITLE
1.7.2 and lower should be marked vulnerable (2fa bruteforcable).

### ISSUE THREAD

**Issue by LeoniePhiline** [laravel/fortify#190]
- Fortify Version: 1.7.2

### Description:
New installations of 1.7.3 are no longer vulnerable for brute-forcing the 2nd factor.

Installations of 1.7.2 and earlier - [even if updated](https://github.com/laravel/fortify/issues/191) - are vulnerable.

**Comment by driesvints** [comment]
How would we mark them as vulnerable?

**Comment by driesvints** [comment]
Ah you probably mean through GitHub. I'll check with Taylor.
