### ISSUE TITLE
Spaces in 2FA codes

### ISSUE THREAD

**Issue by oberrich** [laravel/fortify#196]
- Fortify Version: v1.7.4
 
Google Authenticator formats 2FA codes as `000 000` which leads some users to enter 2FA codes with a space as well in which case their login will be rejected.
In my opinion it's reasonable to expect 2FA codes to get stripped of whitespaces.

I have implemented this in my app by changing
https://github.com/laravel/fortify/blob/2ca0c06bf7385d26730cfc3783865a9c06a51f63/src/Http/Requests/TwoFactorLoginRequest.php#L55-L60
to
```php
    public function hasValidCode()
    {
        if (! $this->code) {
            return false;
        }

        $code = str_replace(' ', '', $this->code);

        return app(TwoFactorAuthenticationProvider::class)->verify(
            decrypt($this->challengedUser()->two_factor_secret), $code
        );
    }
```

**Comment by driesvints** [comment]
I've tried both Twitter and GitHub which enforce input validation to provide a proper formatted 2FA code (without spaces). This should therefor be enforced in userland, not in Fortify.
