### ISSUE TITLE
Override fortify route paths

### ISSUE THREAD

**Issue by ekrist1** [laravel/fortify#20]
I haven't found any ways to override the register, login and logout paths. For some projects it would be nice to use localized paths (e.g. l8.test/logg-inn). 

Would it be a solution to add the paths to the fority.php config file:

```
'paths' => [
        'create_user' => '/opprett'
    ]
```

and then in the fortify route-file:
`Route::get(config('fortify.paths.create_user')`

**Comment by taylorotwell** [comment]
You can disable the routes via Fortify::ignoreRoutes() and then copy the routes into a file in your own application.

**Comment by shankhadevpadam** [comment]
How Fortify::ignoreRoutes() works. I Fortify::ignoreRoutes() placed in the boot method of FortifyServiceProvider but it still showing the default auth routes when I hit php artisan route:list -c. 
```
| POST     | login                            | Laravel\Fortify\Http\Controllers\AuthenticatedSessionController@store           |
| GET|HEAD | login                            | Laravel\Fortify\Http\Controllers\AuthenticatedSessionController@create          |
| POST     | logout                           | Laravel\Fortify\Http\Controllers\AuthenticatedSessionController@destroy         |
| POST     | register                         | Laravel\Fortify\Http\Controllers\RegisteredUserController@store                 |
| GET|HEAD | register                         | Laravel\Fortify\Http\Controllers\RegisteredUserController@create                |
| POST     | reset-password                   | Laravel\Fortify\Http\Controllers\NewPasswordController@store                    |
| GET|HEAD | reset-password/{token}           | Laravel\Fortify\Http\Controllers\NewPasswordController@create                   |
| GET|HEAD | two-factor-challenge             | Laravel\Fortify\Http\Controllers\TwoFactorAuthenticatedSessionController@create |
| POST     | two-factor-challenge             | Laravel\Fortify\Http\Controllers\TwoFactorAuthenticatedSessionController@store  |
| GET|HEAD | user/confirm-password            | Laravel\Fortify\Http\Controllers\ConfirmablePasswordController@show             |
| POST     | user/confirm-password            | Laravel\Fortify\Http\Controllers\ConfirmablePasswordController@store            |
| GET|HEAD | user/confirmed-password-status   | Laravel\Fortify\Http\Controllers\ConfirmedPasswordStatusController@show         |
| PUT      | user/password                    | Laravel\Fortify\Http\Controllers\PasswordController@update                      |
| PUT      | user/profile-information         | Laravel\Fortify\Http\Controllers\ProfileInformationController@update            |
| DELETE   | user/two-factor-authentication   | Laravel\Fortify\Http\Controllers\TwoFactorAuthenticationController@destroy      |
| POST     | user/two-factor-authentication   | Laravel\Fortify\Http\Controllers\TwoFactorAuthenticationController@store        |
| GET|HEAD | user/two-factor-qr-code          | Laravel\Fortify\Http\Controllers\TwoFactorQrCodeController@show                 |
| POST     | user/two-factor-recovery-codes   | Laravel\Fortify\Http\Controllers\RecoveryCodeController@store                   |
| GET|HEAD | user/two-factor-recovery-codes   | Laravel\Fortify\Http\Controllers\RecoveryCodeController@index    
```
I want to create a multi auth for frontend and backend. so for frontend, i used default fortify routes and for backend i used routes/admin.php  just copying the fortify routes and modify the prefix and name like this. Is this a good way?

```
<?php

use Illuminate\Support\Facades\Route;
use Laravel\Fortify\Features;
use Laravel\Fortify\Http\Controllers\AuthenticatedSessionController;
use Laravel\Fortify\Http\Controllers\ConfirmablePasswordController;
use Laravel\Fortify\Http\Controllers\ConfirmedPasswordStatusController;
use Laravel\Fortify\Http\Controllers\EmailVerificationNotificationController;
use Laravel\Fortify\Http\Controllers\EmailVerificationPromptController;
use Laravel\Fortify\Http\Controllers\NewPasswordController;
use Laravel\Fortify\Http\Controllers\PasswordController;
use Laravel\Fortify\Http\Controllers\PasswordResetLinkController;
use Laravel\Fortify\Http\Controllers\ProfileInformationController;
use Laravel\Fortify\Http\Controllers\RecoveryCodeController;
use Laravel\Fortify\Http\Controllers\RegisteredUserController;
use Laravel\Fortify\Http\Controllers\TwoFactorAuthenticatedSessionController;
use Laravel\Fortify\Http\Controllers\TwoFactorAuthenticationController;
use Laravel\Fortify\Http\Controllers\TwoFactorQrCodeController;
use Laravel\Fortify\Http\Controllers\VerifyEmailController;

Route::group(['middleware' => config('fortify.middleware', ['web']), 'prefix' => 'admin', 'as' => 'admin.'], function () {
    // Authentication...
    Route::get('/login', function () {
    	return view('auth.login');
    })->name('login');

    $limiter = config('fortify.limiters.login');

    Route::post('/login', [AuthenticatedSessionController::class, 'store'])
        ->middleware(array_filter([
            'guest',
            $limiter ? 'throttle:'.$limiter : null,
        ]));

    Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])
        ->name('logout');

    // Password Reset...
    if (Features::enabled(Features::resetPasswords())) {
        Route::get('/forgot-password', [PasswordResetLinkController::class, 'create'])
            ->middleware(['guest'])
            ->name('password.request');

        Route::post('/forgot-password', [PasswordResetLinkController::class, 'store'])
            ->middleware(['guest'])
            ->name('password.email');

        Route::get('/reset-password/{token}', [NewPasswordController::class, 'create'])
            ->middleware(['guest'])
            ->name('password.reset');

        Route::post('/reset-password', [NewPasswordController::class, 'store'])
            ->middleware(['guest'])
            ->name('password.update');
    }

    // Registration...
    if (Features::enabled(Features::registration())) {
        Route::get('/register', [RegisteredUserController::class, 'create'])
            ->middleware(['guest'])
            ->name('register');

        Route::post('/register', [RegisteredUserController::class, 'store'])
            ->middleware(['guest']);
    }

    // Email Verification...
    if (Features::enabled(Features::emailVerification())) {
        Route::get('/email/verify', [EmailVerificationPromptController::class, '__invoke'])
            ->middleware(['auth'])
            ->name('verification.notice');

        Route::get('/email/verify/{id}/{hash}', [VerifyEmailController::class, '__invoke'])
            ->middleware(['auth', 'signed', 'throttle:6,1'])
            ->name('verification.verify');

        Route::post('/email/verification-notification', [EmailVerificationNotificationController::class, 'store'])
            ->middleware(['auth', 'throttle:6,1'])
            ->name('verification.send');
    }

    // Profile Information...
    if (Features::enabled(Features::updateProfileInformation())) {
        Route::put('/user/profile-information', [ProfileInformationController::class, 'update'])
            ->middleware(['auth']);
    }

    // Passwords...
    if (Features::enabled(Features::updatePasswords())) {
        Route::put('/user/password', [PasswordController::class, 'update'])
            ->middleware(['auth']);
    }

    // Password Confirmation...
    Route::get('/user/confirm-password', [ConfirmablePasswordController::class, 'show'])
        ->middleware(['auth'])
        ->name('password.confirm');

    Route::post('/user/confirm-password', [ConfirmablePasswordController::class, 'store'])
        ->middleware(['auth']);

    Route::get('/user/confirmed-password-status', [ConfirmedPasswordStatusController::class, 'show'])
        ->middleware(['auth'])
        ->name('password.confirmation');

    // Two Factor Authentication...
    if (Features::enabled(Features::twoFactorAuthentication())) {
        Route::get('/two-factor-challenge', [TwoFactorAuthenticatedSessionController::class, 'create'])
            ->middleware(['guest'])
            ->name('two-factor.login');

        Route::post('/two-factor-challenge', [TwoFactorAuthenticatedSessionController::class, 'store'])
            ->middleware(['guest']);

        $twoFactorMiddleware = Features::optionEnabled(Features::twoFactorAuthentication(), 'confirmPassword')
            ? ['auth', 'password.confirm']
            : ['auth'];

        Route::post('/user/two-factor-authentication', [TwoFactorAuthenticationController::class, 'store'])
            ->middleware($twoFactorMiddleware);

        Route::delete('/user/two-factor-authentication', [TwoFactorAuthenticationController::class, 'destroy'])
            ->middleware($twoFactorMiddleware);

        Route::get('/user/two-factor-qr-code', [TwoFactorQrCodeController::class, 'show'])
            ->middleware($twoFactorMiddleware);

        Route::get('/user/two-factor-recovery-codes', [RecoveryCodeController::class, 'index'])
            ->middleware($twoFactorMiddleware);

        Route::post('/user/two-factor-recovery-codes', [RecoveryCodeController::class, 'store'])
            ->middleware($twoFactorMiddleware);
    }
});

```

**Comment by BulgarianHealer** [comment]
> How Fortify::ignoreRoutes() works. I placed Fortify::ignoreRoutes() in the boot method of FortifyServiceProvider but it still showing the default auth routes when I hit php artisan route:list -c.
> 
> ```
> | POST     | login                            | Laravel\Fortify\Http\Controllers\AuthenticatedSessionController@store           |
> | GET|HEAD | login                            | Laravel\Fortify\Http\Controllers\AuthenticatedSessionController@create          |
> | POST     | logout                           | Laravel\Fortify\Http\Controllers\AuthenticatedSessionController@destroy         |
> | POST     | register                         | Laravel\Fortify\Http\Controllers\RegisteredUserController@store                 |
> | GET|HEAD | register                         | Laravel\Fortify\Http\Controllers\RegisteredUserController@create                |
> | POST     | reset-password                   | Laravel\Fortify\Http\Controllers\NewPasswordController@store                    |
> | GET|HEAD | reset-password/{token}           | Laravel\Fortify\Http\Controllers\NewPasswordController@create                   |
> | GET|HEAD | two-factor-challenge             | Laravel\Fortify\Http\Controllers\TwoFactorAuthenticatedSessionController@create |
> | POST     | two-factor-challenge             | Laravel\Fortify\Http\Controllers\TwoFactorAuthenticatedSessionController@store  |
> | GET|HEAD | user/confirm-password            | Laravel\Fortify\Http\Controllers\ConfirmablePasswordController@show             |
> | POST     | user/confirm-password            | Laravel\Fortify\Http\Controllers\ConfirmablePasswordController@store            |
> | GET|HEAD | user/confirmed-password-status   | Laravel\Fortify\Http\Controllers\ConfirmedPasswordStatusController@show         |
> | PUT      | user/password                    | Laravel\Fortify\Http\Controllers\PasswordController@update                      |
> | PUT      | user/profile-information         | Laravel\Fortify\Http\Controllers\ProfileInformationController@update            |
> | DELETE   | user/two-factor-authentication   | Laravel\Fortify\Http\Controllers\TwoFactorAuthenticationController@destroy      |
> | POST     | user/two-factor-authentication   | Laravel\Fortify\Http\Controllers\TwoFactorAuthenticationController@store        |
> | GET|HEAD | user/two-factor-qr-code          | Laravel\Fortify\Http\Controllers\TwoFactorQrCodeController@show                 |
> | POST     | user/two-factor-recovery-codes   | Laravel\Fortify\Http\Controllers\RecoveryCodeController@store                   |
> | GET|HEAD | user/two-factor-recovery-codes   | Laravel\Fortify\Http\Controllers\RecoveryCodeController@index    
> ```
> 
> I want to create a multi auth for frontend and backend. so for frontend, i used default fortify routes and for backend i used routes/admin.php just copying the fortify routes and modify the prefix and name like this. Is this a good way?
> 
> ```
> <?php
> 
> use Illuminate\Support\Facades\Route;
> use Laravel\Fortify\Features;
> use Laravel\Fortify\Http\Controllers\AuthenticatedSessionController;
> use Laravel\Fortify\Http\Controllers\ConfirmablePasswordController;
> use Laravel\Fortify\Http\Controllers\ConfirmedPasswordStatusController;
> use Laravel\Fortify\Http\Controllers\EmailVerificationNotificationController;
> use Laravel\Fortify\Http\Controllers\EmailVerificationPromptController;
> use Laravel\Fortify\Http\Controllers\NewPasswordController;
> use Laravel\Fortify\Http\Controllers\PasswordController;
> use Laravel\Fortify\Http\Controllers\PasswordResetLinkController;
> use Laravel\Fortify\Http\Controllers\ProfileInformationController;
> use Laravel\Fortify\Http\Controllers\RecoveryCodeController;
> use Laravel\Fortify\Http\Controllers\RegisteredUserController;
> use Laravel\Fortify\Http\Controllers\TwoFactorAuthenticatedSessionController;
> use Laravel\Fortify\Http\Controllers\TwoFactorAuthenticationController;
> use Laravel\Fortify\Http\Controllers\TwoFactorQrCodeController;
> use Laravel\Fortify\Http\Controllers\VerifyEmailController;
> 
> Route::group(['middleware' => config('fortify.middleware', ['web']), 'prefix' => 'admin', 'as' => 'admin.'], function () {
>     // Authentication...
>     Route::get('/login', function () {
>     	return view('auth.login');
>     })->name('login');
> 
>     $limiter = config('fortify.limiters.login');
> 
>     Route::post('/login', [AuthenticatedSessionController::class, 'store'])
>         ->middleware(array_filter([
>             'guest',
>             $limiter ? 'throttle:'.$limiter : null,
>         ]));
> 
>     Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])
>         ->name('logout');
> 
>     // Password Reset...
>     if (Features::enabled(Features::resetPasswords())) {
>         Route::get('/forgot-password', [PasswordResetLinkController::class, 'create'])
>             ->middleware(['guest'])
>             ->name('password.request');
> 
>         Route::post('/forgot-password', [PasswordResetLinkController::class, 'store'])
>             ->middleware(['guest'])
>             ->name('password.email');
> 
>         Route::get('/reset-password/{token}', [NewPasswordController::class, 'create'])
>             ->middleware(['guest'])
>             ->name('password.reset');
> 
>         Route::post('/reset-password', [NewPasswordController::class, 'store'])
>             ->middleware(['guest'])
>             ->name('password.update');
>     }
> 
>     // Registration...
>     if (Features::enabled(Features::registration())) {
>         Route::get('/register', [RegisteredUserController::class, 'create'])
>             ->middleware(['guest'])
>             ->name('register');
> 
>         Route::post('/register', [RegisteredUserController::class, 'store'])
>             ->middleware(['guest']);
>     }
> 
>     // Email Verification...
>     if (Features::enabled(Features::emailVerification())) {
>         Route::get('/email/verify', [EmailVerificationPromptController::class, '__invoke'])
>             ->middleware(['auth'])
>             ->name('verification.notice');
> 
>         Route::get('/email/verify/{id}/{hash}', [VerifyEmailController::class, '__invoke'])
>             ->middleware(['auth', 'signed', 'throttle:6,1'])
>             ->name('verification.verify');
> 
>         Route::post('/email/verification-notification', [EmailVerificationNotificationController::class, 'store'])
>             ->middleware(['auth', 'throttle:6,1'])
>             ->name('verification.send');
>     }
> 
>     // Profile Information...
>     if (Features::enabled(Features::updateProfileInformation())) {
>         Route::put('/user/profile-information', [ProfileInformationController::class, 'update'])
>             ->middleware(['auth']);
>     }
> 
>     // Passwords...
>     if (Features::enabled(Features::updatePasswords())) {
>         Route::put('/user/password', [PasswordController::class, 'update'])
>             ->middleware(['auth']);
>     }
> 
>     // Password Confirmation...
>     Route::get('/user/confirm-password', [ConfirmablePasswordController::class, 'show'])
>         ->middleware(['auth'])
>         ->name('password.confirm');
> 
>     Route::post('/user/confirm-password', [ConfirmablePasswordController::class, 'store'])
>         ->middleware(['auth']);
> 
>     Route::get('/user/confirmed-password-status', [ConfirmedPasswordStatusController::class, 'show'])
>         ->middleware(['auth'])
>         ->name('password.confirmation');
> 
>     // Two Factor Authentication...
>     if (Features::enabled(Features::twoFactorAuthentication())) {
>         Route::get('/two-factor-challenge', [TwoFactorAuthenticatedSessionController::class, 'create'])
>             ->middleware(['guest'])
>             ->name('two-factor.login');
> 
>         Route::post('/two-factor-challenge', [TwoFactorAuthenticatedSessionController::class, 'store'])
>             ->middleware(['guest']);
> 
>         $twoFactorMiddleware = Features::optionEnabled(Features::twoFactorAuthentication(), 'confirmPassword')
>             ? ['auth', 'password.confirm']
>             : ['auth'];
> 
>         Route::post('/user/two-factor-authentication', [TwoFactorAuthenticationController::class, 'store'])
>             ->middleware($twoFactorMiddleware);
> 
>         Route::delete('/user/two-factor-authentication', [TwoFactorAuthenticationController::class, 'destroy'])
>             ->middleware($twoFactorMiddleware);
> 
>         Route::get('/user/two-factor-qr-code', [TwoFactorQrCodeController::class, 'show'])
>             ->middleware($twoFactorMiddleware);
> 
>         Route::get('/user/two-factor-recovery-codes', [RecoveryCodeController::class, 'index'])
>             ->middleware($twoFactorMiddleware);
> 
>         Route::post('/user/two-factor-recovery-codes', [RecoveryCodeController::class, 'store'])
>             ->middleware($twoFactorMiddleware);
>     }
> });
> ```

Why boot? Must be in register.
