### ISSUE TITLE
Current 2FA solution can lock users out of their accounts

### ISSUE THREAD

**Issue by LeoniePhiline** [laravel/fortify#201]
- Version: v1.7.4
- Laravel Version: v8.22.1
- PHP Version: v7.4.13

### Description:

The current two factor authentication solution sets 2fa to enabled without requiring a confirmation (via TOTP) that the authenticator app is actually set up.

### Steps To Reproduce:

The current solution works like this:

1. `POST /user/two-factor-authentication`, the user's `two_factor_secret` is stored. (2fa is now enabled!)
2. `GET /user/two-factor-qr-code`, show QR code and ask user to scan the code with their app.
3. `GET /user/two-factor-recovery-codes`, show recovery codes and ask the user to save them.
4. User abandons the process before setting up their authenticator app or saving the recovery codes and is now **locked out of their account**.

They could abandon the process because they first need to choose one of the many TOTP generators in the app store, and get side tracked, or their session times out, or they click the back button, or close their tab, or their computer crashes, ... Definitely 2fa must not be enabled before it is confirmed by a generated OTP.

### How To Fix It:

1. `GET /user/two-factor-qr-code` generates a QR code from a new two factor secret that is **stored in the session**.
2. `GET /user/two-factor-recovery-codes`, show the recovery codes to the user, ask them to save them. 
3. The user is asked to set up their authenticator app with this QR code and enter a resulting TOTP code. This confirms that they have set up their authenticator (else they cannot generate a valid code), and can also (by written explanation) be used as confirmation that recovery codes were stored in a safe place.
4. `POST /user/two-factor-authentication`, receives a new parameter: `code`. **The code is validated using the two factor secret stored in the session.**
5. If the code is valid, **the two factor secret from the session is written into the user table** (= enabling 2fa, now for real). If not, then the response indicates that the user did not enter a valid code and must re-try.

**Comment by driesvints** [comment]
This issue basically ties into https://github.com/laravel/jetstream/issues/74. While I agree it would be better if we required it, it's opinionated for sure. We could make this an opt-in feature for Fortify 1.x so we can implement it in Jetstream together with https://github.com/laravel/jetstream/issues/74.

**Comment by LeoniePhiline** [comment]
Having it as an opt in feature for now to avoid the breaking change until the next major version sounds good to me. 

I kindly disagree that this is opinionated, though. ;-)

——

By the way, is there a plan for a RequireSecondFactor confirmation middleware (with timeout) that works like the laravel core RequirePassword middleware?

A developer would want to force the “highest security level” confirmation for certain actions, while only asking for password confirmation in other cases. 

A third possible middleware might use the “highest available”, which is OTP if 2fa is enabled, on the user record, else require password.

**Comment by driesvints** [comment]
> By the way, is there a plan for a RequireSecondFactor confirmation middleware (with timeout) that works like the laravel core RequirePassword middleware?

Not at this time.

**Comment by LeoniePhiline** [comment]
Would you be interested in a PR or would that be trashed anyway?

**Comment by driesvints** [comment]
@LeoniePhiline Taylor handles the PR's so I can't really say sorry.

**Comment by markokeeffe** [comment]
@LeoniePhiline a lot of apps I use ask for confirmation of one-time password when the QR code is presented to the user. I'm handling this by adding a `two_factor_confirmed` boolean column to my `users` table. This will only be set to `true` when the user enters a valid one-time password in the 2FA setup process.

**Comment by LeoniePhiline** [comment]
@markokeeffe Definitely a valid approach. This must be part of Fortify, though! Most developers might just not notice the implementation is broken until the first users have been locked out.

**Comment by radudiaconu0** [comment]
Any update on this?

**Comment by nicolus** [comment]
@markokeeffe : That sound like a decent solution, but the issue I have is that the part that check if a user had 2FA is in Laravel\Fortify\Actions\RedirectIfTwoFactorAuthenticatable::handle and directly check if the two_factor_secret field is not null :

```php
if (optional($user)->two_factor_secret &&
    in_array(TwoFactorAuthenticatable::class, class_uses_recursive($user))) {
    return $this->twoFactorChallengeResponse($request, $user);
}
```

So I have no idea how to cleanly modify this behavior since this action is not published but stays in the vendor directory.

**Comment by driesvints** [comment]
@nicolus appreciating PRs to the docs if you think something can be explained better 👍

**Comment by radudiaconu0** [comment]
@nicolus so where u make that field true if it's confirmed. I don't see that part in your code

**Comment by nicolus** [comment]
@radudiaconu0 : If you're interested I've done a full write up here :
https://dev.to/nicolus/laravel-fortify-implement-2fa-in-a-way-that-won-t-let-users-lock-themselves-out-2ejk

**Comment by radudiaconu0** [comment]
@nicolus Thanks

**Comment by James4645** [comment]
If I could put in my 2 cents. I would strongly disagree that its opinionated and instead say its best practice to confirm the user has correctly enabled and configured their authentication app before enabling 2FA. I'm glad there is a workaround but I think it should be core to the implementation.

**Comment by dmandrade** [comment]
I created a patch to fix this issue directly in the fortify package, with this solution the 2FA will only be required after the complete configuration:
[https://gist.github.com/dmandrade/c2381e00af6234162f61d6d6593addac](https://gist.github.com/dmandrade/c2381e00af6234162f61d6d6593addac)

To apply it automatically just install the **vaimo/composer-patches** package

I'm going to do a PR with an optional solution, which is not ideal but at least it won't create breaking changes

**Comment by dmandrade** [comment]
I have a fork with such an implementation, I currently use it as a patch in fortify and jetstream.
[https://gist.github.com/dmandrade/c2381e00af6234162f61d6d6593addac](https://gist.github.com/dmandrade/c2381e00af6234162f61d6d6593addac)

I could do a PR with an opt-in feature

**Comment by patrickomeara** [comment]
@taylorotwell @driesvints Are either of you able to confirm that whatever solution the Laravel team implements will be backward compatible with the current 2fa codes that users have? I assume the answer is yes.

We have a looming regulatory cut off date for 2fa, and I'm trying to gauge whether to keep holding out on the official fix for this or not. I'm happy to implement a workaround in the meantime if users don't need to enable 2fa again once the official fix is out.

**Comment by driesvints** [comment]
There's no upcoming date for a fix sorry. Best that you roll your own for now.

**Comment by patrickomeara** [comment]
Thanks @driesvints 

Am I correct in saying that whatever the confirmation solution looks like the stored OTP algorithm for each user will be unchanged?

**Comment by driesvints** [comment]
@patrickomeara I can't say anything about that unless I dig in and I don't have the time for that right now.

**Comment by securit** [comment]
My 2c, using a session key/cache approach might be a way to resolve the man-in-the-middle vulnerability of the token. 

The current implementation of 2FA allows a generated token to be re-used any time within the time-step window . The [RFC](https://datatracker.ietf.org/doc/html/rfc6238#section-5.2) talks about the implications of the time-step window and says:

> Second, the next different OTP must be generated in the next time-step window.  A user must wait until the clock moves to the next time-step window from the last submission. 

The Laravel implementation does not conform to this part of the standard, thus allowing a man-in-the-middle replay.

Simply put, store the code and the timestamp in the session. If the code is the same as the one in the session and the timestamp is within the time-step window, then the authentication should be rejected.

**Comment by LeoniePhiline** [comment]
Very good point. May be better in a new issue?

**Comment by driesvints** [comment]
@securit doesn't the rate limiting of the Two factor auth challenge already prevent this?

**Comment by securit** [comment]
I don’t believe so.

**Comment by driesvints** [comment]
@securit why? The current rate limiting already prevents entering the 2FA more than 5 times during a minute: https://github.com/laravel/fortify/blob/1.x/stubs/FortifyServiceProvider.php#L46. It's based on the login ID in session from the user that entered a correct username/password. So I don't see how that's insecure? Happy to be proven otherwise if you can explain.

**Comment by securit** [comment]
That gives me 4 more attempts to re-use of the current QR code during that minute. The RFC says that once a QR code has been used. I should not be able to be used again. That is where the “ONE” in OTP (One Time Passcode) comes from.

Kind regards

Greg Munro
***@***.***
+64 22 623 0406

**Comment by driesvints** [comment]
@securit 5 attempts during a minute hardly sound like a MITM vulnerability to me. I think you're referring to a brute force attack instead? That also, doesn't seems like a vulnerability with rate limiting in play. 

I don't want to downplay your concerns because you are right that things can be done slightly better here. But I don't see any major security risks with the current way things work. We'd appreciate PR's to improve this though.

Also, let's keep this discussion out of this issue so we can focus on the topic at hand. If you want to address this feel free to send in a PR, thanks.

**Comment by x7ryan** [comment]
@driesvints FWIW I agree that is not desired. It wouldn't be MITM I believe the correct categorization would be a Replay Attack. Because if an attacker were to see a user enter a valid code, and also knows or saw the Username and Password there is a short window of time where they could login with it as well. The code is only supposed to be valid for a single use. Even just a short lived cache entry noting the user and code used to check attempts against to ensure it wasn't used already should be sufficient.

**Comment by driesvints** [comment]
Thanks @x7ryan. I'll note that internally to check into at some point.

**Comment by driesvints** [comment]
Taylor has been working on this yesterday: https://github.com/laravel/fortify/pull/357

**Comment by securit** [comment]
Yup, saw that and was very pleased :)

Thankyou

**Comment by LeoniePhiline** [comment]
@driesvints 
As fortify 2fa is vulnerable to replay attacks, a security advisory should be published.

**Comment by driesvints** [comment]
@LeoniePhiline what replay attack?

**Comment by taylorotwell** [comment]
@LeoniePhiline will consider adding that in the future - however I'm not sure I would consider that a super serious vulnerability? A person is literally standing there watching you type, knows your username and password already, and then runs to another computer to login as you before the code expires?

**Comment by taylorotwell** [comment]
If you want to contribute to this open source library feel free to do so.

**Comment by driesvints** [comment]
This one will be released today.

**Comment by driesvints** [comment]
A Jetstream update is still pending btw.

**Comment by driesvints** [comment]
@x7ryan @LeoniePhiline @securit I attempted at fixing that issue you described here: https://github.com/laravel/fortify/pull/366. Would appreciate your thoughts if that looked good or not.
