### ISSUE TITLE
Login with SSO (Keycloak)

### ISSUE THREAD

**Issue by homeoftheunits** [laravel/fortify#207]
Hi,

we have many Laravel Applications in our universe. Now we want to handle the Login with one Loginpage. We want to use Keycloak as SSO Service here. 

Is it possible to integrate Keycloak in fortify?

Cheers
Ralf

**Comment by driesvints** [comment]
We don't have plans for this atm, sorry.

**Comment by homeoftheunits** [comment]
Yes, this is not a Question how can you do that. But whether i could implement it by myself and whats the best way to do that

**Comment by driesvints** [comment]
Best to try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
