### ISSUE TITLE
Missing case for password rules combination

### ISSUE THREAD

**Issue by stuartcusackie** [laravel/fortify#212]
- Fortify Version: 1.7.5
- Laravel Version: 8.25.0

### Description:

I have set up my password rules like so:

```
(new Password)
  ->length(10)
  ->requireNumeric()
  ->requireSpecialCharacter(),
```

It seems there is no case in the [message() switch](https://github.com/laravel/fortify/blob/e309222bc1534718e2508954af145f5967bb5039/src/Rules/Password.php#L76) for the above and the error always appears as:
`The password must be at least 10 characters.`
even if you've met the character count requirements.

**Steps:**

1. Create PasswordValidationRules.php in app/Actions/Fortify.
2. Place content:
```
<?php

namespace App\Actions\Fortify;

use Laravel\Fortify\Rules\Password;

trait PasswordValidationRules
{
    /**
     * Get the validation rules used to validate passwords.
     *
     * @return array
     */
    protected function passwordRules()
    {
        return [
        	'required',
        	'string',
        	(new Password)
        		  ->length(10)
                          ->requireNumeric()
                          ->requireSpecialCharacter(),
        	'confirmed',
        ];
    }
}
```

**Comment by driesvints** [comment]
Please provide more specific steps to reproduce this issue.

**Comment by stuartcusackie** [comment]
I've updated my original post above. Thank you.

**Comment by driesvints** [comment]
Yep I see it now. I'll send in a PR.
