### ISSUE TITLE
Request: add names to the generated URI

### ISSUE THREAD

**Issue by fcolecumberri** [laravel/fortify#215]
As can be seen here https://github.com/laravel/fortify/blob/1.x/routes/routes.php the next routes are lacking a name:

```
POST   /login
POST   /register
POST   /two-factor-challenge
POST   /user/confirm-password
POST   /user/two-factor-authentication
DELETE /user/two-factor-authentication
GET    /user/two-factor-qr-code
GET    /user/two-factor-recovery-codes
POST   /user/two-factor-recovery-codes
```
I don't know if there is a reason for that, I would make a pull request but I don't know what would be a good name for those routes. Could you give them a name?

I am still starting on Laravel and I watched https://www.youtube.com/watch?v=7lalb6HtR1c so I am trying to make my whole application links use names. If there are no plans to give name to this routes, is there any way to give them name on other place?

**Comment by driesvints** [comment]
Some like the login and register one don't need one because their GET equivalent have the same url structure. Feel free to attempt a PR for other ones if you want 👍

**Comment by fcolecumberri** [comment]
done https://github.com/laravel/fortify/pull/216
