### ISSUE TITLE
Only allow two-factor-challenge routes when user is logged in

### ISSUE THREAD

**Issue by kiwina** [laravel/fortify#218]
- Fortify Version: 1.6.1
- Laravel Version: 8.26.1
- PHP Version: 8
- Database Driver & Version:

### Description:
In jetstream the two-factor-challenge route is accessible even when the user is not logged in.
Technically the route should redirect to the login screen. not sure if this happen on vanilla implementation

**Comment by driesvints** [comment]
We don't have any immediate plans to change anything here. Feel free to attempt a PR if you feel anything can be improved 👍
