### ISSUE TITLE
Disabling a features doesn't disable routes.

### ISSUE THREAD

**Issue by piotranon** [laravel/fortify#220]
- Fortify Version: v1.7.5
- Laravel Version: 8.27.0
- PHP Version: 7.4.10
- Database Driver & Version: 

### Description:

Disabling all routes doesn't disable routes which are only used to registration.

![image](https://user-images.githubusercontent.com/40769535/107820875-d5c82200-6d7b-11eb-9e11-cb238164b340.png)

Routes:

- user/confirm-password - POST
- user/confirmed-password-status - GET|HEAD

![image](https://user-images.githubusercontent.com/40769535/107820910-e2e51100-6d7b-11eb-90d9-563e40728585.png)

Removing confirm validation rule from PasswordValidationRules didn't help.

### Steps To Reproduce:

Disable features in fortify.
Clear cache.

**Comment by driesvints** [comment]
These aren't used for registration but, for example, for the confirm password prompt in Jetstream. They should always be active.

**Comment by TimVanHerwijnen** [comment]
Fix described in #117 

Make sure `App\Providers\FortifyServiceProvider` is registered in config/app.php

Then add `Fortify::ignoreRoutes();` under the `register()` method inside your `App\Providers\FortifyServiceProvider`

**Comment by francoism90** [comment]
@timyourivh Thanks! I needed this to get it working. :)
