### ISSUE TITLE
Logout redirect not working

### ISSUE THREAD

**Issue by Jusdon** [laravel/fortify#223]
- Fortify Version: 1.7.5
- Laravel Version: 8.27.0
- PHP Version: 7.4.0
- Database Driver & Version: mysql 5.7.28

### Description:
The Laravel Fortify logout route does not redirect correctly. A 404 error appears when you log out and if you press F5, you will only be redirected correctly

### Steps To Reproduce:
Log in normally and then press the logout "button"

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by Jusdon** [comment]
Hey,
sorry it was my mistake! I found an issue in my code!
I was just confused and couldn't explain the mistake. Ultimately, the error had nothing to do with an alleged 404 error.
