### ISSUE TITLE
Cannot verify user email in safari

### ISSUE THREAD

**Issue by chucklin72** [laravel/fortify#224]
- Fortify Version: Latest
- Laravel Version: 8.12
- PHP Version: 7.4
- Database Driver & Version:

### Description:
Cannot verify email when developing locally using Safari browser.
User is stuck in the look of browser asking to verify. Using Mailhog to click on the verify link.
in laravel/fortify/routes.php

        Route::get('/email/verify/{id}/{hash}', [VerifyEmailController::class, '__invoke'])
            ->middleware(['auth', 'signed', 'throttle:6,1'])
            ->name('verification.verify');

auth returns true, signed return true. not a throttling issue.

Works perfectly on chrome.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by lucaros97** [comment]
Hi @driesvints seems like I get the same problem i found [here](https://github.com/laravel/jetstream/issues/686). 
I just verified what @chucklin72 said and I get the same error.
Email verification it's working in all browser except Safari.

**Comment by driesvints** [comment]
I can't reproduce this. I used all the steps from above with the same stack and it works just fine for me in Safari.

**Comment by lostdesign** [comment]
I **cannot** reproduce this on macOS Big Sur (11.0.1) and Safari (14.0.1).

I am using valet (2.13.19) and docker (Docker version 20.10.2, build 2291f61 / docker-compose version 1.27.4, build 40524192). 

Demo Repo here [Demo repo here](https://github.com/lostdesign/jetfortmailverify)

Steps that I did:
```
laravel new foo
cd foo
valet secure foo
composer require laravel/jetstream
php artisan jetstream:install inertia --teams
npm install && npm run dev
php artisan migrate
```

Then I implemented [Verification as per docs](https://jetstream.laravel.com/2.x/features/registration.html#email-verification) aka `class User extends Authenticatable implements MustVerifyEmail` and enabled in `config/fortify.php` the `Features::emailVerification(),`.

Registered a user, caught the mail in mail trap, copied the URL, pasted in safari, hit enter, user logged in and verified.


```
Laravel v8.28.1 (PHP v7.4.14)
"inertiajs/inertia-laravel": "^0.3.5",
"laravel/framework": "^8.12",
"laravel/jetstream": "^2.2",
```

![Kapture 2021-02-19 at 11 42 18](https://user-images.githubusercontent.com/5164617/108494275-9df33a00-72a7-11eb-988e-a919357b08f8.gif)

**Comment by lucaros97** [comment]
Seems to be a session/cookie problem. If I was previously logged in with another account and then try to register and verify email the error occurs.
Tried to clear my cookies and everything works

**Comment by chucklin72** [comment]
I noticed you are using mailtrap. I tried this and found that the problem occurs when I'm using mailhog. 
Then i had mailhog running in chrome and copy the email link and pasted it safari, voila it works.

I think @lucaros97 is right, this is some weird cookie thing.
