### ISSUE TITLE
problem at create register

### ISSUE THREAD

**Issue by nikos25** [laravel/fortify#228]
Hello good evening, I am working with Fortify in my project, the register and login work fine, but I have this problem: I enter with my username and password, I go to the registration form to create a new account, it is created but when I return to home I see that the login is the user who registered previously, then I must avoid that when creating a user account this is logged automatically....

Any idea what could be happening?

Greetings from chile

Translated with www.DeepL.com/Translator (free version)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
