### ISSUE TITLE
Redirect 2fa challenge route if accessed directly

### ISSUE THREAD

**Issue by amiranagram** [laravel/fortify#231]
I'm not sure what's the common approach, but is it really OK to allow access to the /two-factor-challenge route if accessed directly without first logging in?

**Comment by driesvints** [comment]
Yes, the user isn't logged in yet after filling out the login/password screen. They're only authenticated when the 2FA also succeeds.

**Comment by amiranagram** [comment]
My bad @driesvints, I didn't explain it properly. I meant if you navigate to `/two-factor-challenge` directly without completing the login step (not actually logging in, just submitting the username and password) you are allowed to see the 2fa challenge form.

**Comment by driesvints** [comment]
Thanks for explaining. I've sent a fix here: https://github.com/laravel/fortify/pull/233
