### ISSUE TITLE
Validation errors

### ISSUE THREAD

**Issue by todo4learn** [laravel/fortify#237]
- Fortify Version: 1.7.8
- Laravel Version: 8.x
- PHP Version: 7.4.15
- Database Driver & Version: Mysql 8.0.23

### Description:
Hello, I'm trying Fortify since one week now and I'm stuck on the same problem at two level.
The problem is when I try to update user password, it doesn't show me validation errors (I mean, when for test purpose I leave fields blank)
The same thing when I try to update user informations (name, email... when I leave them blank for test purpose)

### Steps To Reproduce:
Try password update
Try user informations update

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by todo4learn** [comment]
Hi, and sorry if it wasn't the right place about my issue, I'll do like you said and ask on support channel.
But, if someone can provide me a solution or some ways for troubleshooting, I'll be happy !

Thanks.

**Comment by deveti** [comment]
@todo4learn you need to check validation ErrorBag. Something like this:

`
@if ($errors->getBags())
    @foreach ($errors->getBags() as $errorBag)
        <ul>
            @foreach ($errorBag->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    @endforeach
@endif
`
