### ISSUE TITLE
When SPA is used, user verify email is redirected to one URL instead of json response.

### ISSUE THREAD

**Issue by itsnunolemos** [laravel/fortify#241]
- Fortify Version: 8.29.0
- Laravel Version: 1.7.7
- PHP Version: 7.4.14

### Description:
When SPA is used, user verify email is redirected to one URL instead of json response.

### Steps To Reproduce:
1. Create one SPA (single page application) or use Postman and use sanctum and fortify
2. Create one user (with Email Verification on)
2. Verify your email and click in the verification link
3. SPA expect http code `204` or `202` but receive one redirect link

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
