### ISSUE TITLE
Send request to "reset-password" route without password will cause "Undefined index" error

### ISSUE THREAD

**Issue by kurorido** [laravel/fortify#244]
- Fortify Version: 1.7.8
- Laravel Version: 8.34.0
- PHP Version: 7.4.15
- Database Driver & Version: MySQL 8.0

### Description:

The payload sent to "reset-password" route

```
{
    "token": "f46be4baf70e56946d8b17e066afeab45f028afe8dd734b39b2d7442043b5a2f",
    "email": "test@test.com",
}
```

will cause the error in laravel/framework

```
{
    "message": "Undefined index: password",
    "exception": "ErrorException",
    "file": "/vendor/laravel/framework/src/Illuminate/Auth/Passwords/PasswordBroker.php",
    "line": 95,
    "trace": [
        {
            "file": "/vendor/laravel/framework/src/Illuminate/Auth/Passwords/PasswordBroker.php",
            "line": 95,
            "function": "handleError",
            "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
            "type": "->"
        },
   .....
```

### Steps To Reproduce:

Sent the payload above.

### Suggest Solution:

Solution 1:

Modify the Fortify Package in [NewPasswordController.php](https://github.com/laravel/fortify/blob/ee4d41b6638718abf0dfb72dcff081e627b548af/src/Http/Controllers/NewPasswordController.php#L57) to validate password before pass to laravel/framework

Solution 2:

Modify the laravel/framework in [PasswordBroker.php](https://github.com/laravel/framework/blob/28e0f61bba1cbc727383d183b7116eb723de7660/src/Illuminate/Auth/Passwords/PasswordBroker.php#L95) to prevent undefined index

change the line `$password = $credentials['password'];` to `$password = $credentials['password'] ?? null;`

**Comment by driesvints** [comment]
Thanks. A fix has been merged and will be tagged tomorrow.
