### ISSUE TITLE
Password reset issue - Target [Laravel\Fortify\Contracts\ResetPasswordViewResponse] is not instantiable.

### ISSUE THREAD

**Issue by m4aax16** [laravel/fortify#251]
- Fortify Version: 1.7
- Laravel Version: 8.33.1
- PHP Version: 7.4
- Database Driver & Version: MySQL 8

### Description:
Hi,
The password reset function doesn't work. Login, Register & 2FA work like a charm. I'm trying to send a password reset mail to my mail account. After click "Reset Password" button on my email the issue is displayed :

` Target [Laravel\Fortify\Contracts\ResetPasswordViewResponse] is not instantiable. `

What I have already done : 
=> Cleared cache
=> Checked whether the Fortify service provider is integrated 
= > Updated the package
=> Checked whether a password reset view exists

Note : I'm not using Jetstream

### Steps To Reproduce:
1. Install the package
2. Try to reset the password
3. Click on Mail link
4. Reproduced

**Comment by m4aax16** [comment]
Solved

**Comment by paladisco** [comment]
@m4aax16 How did you solve it? Experiencing the exact same issue.

**Comment by m4aax16** [comment]
@paladisco I have watched and followed this tutorial : https://www.youtube.com/watch?v=7pvBvDAbXG0&t=578s
