### ISSUE TITLE
Enhancement - Password updated acknowledgement email

### ISSUE THREAD

**Issue by thomasrd1** [laravel/fortify#252]
These days, it's very common to receive and email acknowledgement when you have changed your password.

- when a user changes their password via the reset password form
- when a user changes their password via the change password form

`Hi Thomas,
You have just changed your password on {siteurl}. If this was not you, please contact us immediately.
If this was you please ignore this email.
`

**Comment by driesvints** [comment]
We don't have plans for this ourselves atm. You're always free to attempt a PR. Thanks
