### ISSUE TITLE
Make 2FA extendable using something like drivers found in other parts of Laravel

### ISSUE THREAD

**Issue by James4645** [laravel/fortify#266]
It's been mentioned before (#257, and probably others I'm not aware of) to implement other types of 2FA, which was rejected. And understandably so, implementing all possible forms of 2FA and related logic just isn't possible and I would say almost definitely out of scope for Fortify.

My suggestion is to instead make the 2FA system extensible. I am thinking of something like drivers, found elsewhere in Laravel such as notifications and mail. The idea is the basic flow to require 2FA would be enforced by Fortify but passed off to a driver that would then handle the specifics of the implementation.  Then the current TOTP based 2FA logic could be extracted out into a default driver that comes with Fortify but the community has as easily extensible way to create other specific 2FA implementations such as SMS or U2F (hardware security key).

**Comment by driesvints** [comment]
Sounds reasonable but I don't know how practical this would be code-wise and if Taylor wants to maintain the code needed for this. It's best that you do a practical proposal in form of a PR so we can look at the code that would be needed for this. If the PR isn't accepted you can still use a fork if you want. Thanks

**Comment by James4645** [comment]
That's unfortunate because as much as I like the idea it's well beyond my ability to actually even attempt to implement such a thing. Which is why I was hoping to make the suggestion here rather than just submitting a PR.
