### ISSUE TITLE
Call to undefined method Illuminate\Auth\DatabaseUserProvider::getModel()

### ISSUE THREAD

**Issue by valtonia** [laravel/fortify#268]
- Fortify Version: 1.7.12
- Laravel Version: 8.x (framework version 8.40.0)

### Description:
`Laravel\Fortify\Actions\RedirectIfTwoFactorAuthenticatable` calls a non-interface method `->getModel()` on the user provider class obtained from the  constructor argument `$guard`.

`Illuminate\Contracts\Auth\UserProvider` does not declare `->getModel()` as a method but `Illuminate\Auth\EloquentUserProvider` implements it whereas `Illumintate\Auth\DatabaseUserProvider` does not.

Fortify should not call methods that are not part of the interface.

### Steps To Reproduce:

Change the user provider setting in `config/auth.php` to use the "database" setting instead of "eloquent".
Attempting to log in throws an error "Call to undefined method Illuminate\\Auth\\DatabaseUserProvider::getModel()"

**Comment by valtonia** [comment]
A temporary workaround for this issue is to disable two-factor auth in `config/fortify.php`

**Comment by driesvints** [comment]
Only Eloquent is supported atm.
