### ISSUE TITLE
Redirect route after reset cannot be modified

### ISSUE THREAD

**Issue by Velka-DEV** [laravel/fortify#271]
- Fortify Version: 1.7 
- Laravel Version: 8.40
- PHP Version: 7.3
- Database Driver & Version: MariaDB 

### Description:

Hi, i just looked into the doc and i don't see anywhere a way to redirect to the correct login view after resetting the password if the login route is not named "login"

### Steps To Reproduce:

Login route name: 'auth.login'

Successfully reseting the password will redirect to route called "login"

**Comment by driesvints** [comment]
Hi there. Please see https://github.com/laravel/fortify/issues/77
