### ISSUE TITLE
Unable to reset password with fortify custom column name

### ISSUE THREAD

**Issue by webtamizhan** [laravel/fortify#273]
- Fortify Version: 1.7.12
- Laravel Version: 8.42.1
- PHP Version: 7.4
- Database Driver & Version: 5.7

### Description:
Unable to reset password, if email column name was other than "email", that i changed in fortify config.

### Steps To Reproduce:
in `trait CanResetPassword` , the `function getEmailForPasswordReset()` only return column name "email", not with fortify config. 

or Is there anything i missed out?

**Comment by driesvints** [comment]
Overwrite `getEmailForPasswordReset` on your model with the value you need.
