### ISSUE TITLE
Home Route Issue

### ISSUE THREAD

**Issue by hexpit** [laravel/fortify#274]
My home route is being returned from a helper function. In RouteServiceProvide if I replace

public const HOME = '/';

with 

public const HOME = homeRoute();

It gives me an error "Expression is not allowed as class constant value".

changing home route variable in fortify configuration couldn't help as helper libraries are not loaded before configuration. Can anyone please provide me a workaround?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
