### ISSUE TITLE
Consider changing parameters on contracts

### ISSUE THREAD

**Issue by Velka-DEV** [laravel/fortify#277]
- Fortify Version: 1.7
- Laravel Version: 8.40
- PHP Version: 7.3
- Database Driver & Version: MySQL

### Description:

Actually array's of data input is pass to contracts functions (Actions like CreateNewUser)

It's not really cool because we can't access other request data, like actually i need to retrieve a cookie on the register request but i can't access it because we don't have the request

Or maybe i miss something

**Comment by driesvints** [comment]
If you want to propose something feel free to send in a PR 👍

**Comment by Velka-DEV** [comment]
PR wating for review: https://github.com/laravel/fortify/pull/278
