### ISSUE TITLE
Clean way to queue up sending email verification notification

### ISSUE THREAD

**Issue by isaac-souza** [laravel/fortify#287]
It is totally doable to queue up email notifications by "hacking up" fortify, however it would be nice if we had support for it out of the box, like setting up a flag in a config file or calling some method on a service provider that would automagically queue up all emails to be sent.

Thanks,

Isaac

**Comment by driesvints** [comment]
Think this issue is best continued in a PR where we can look at some actual code on how to do this. Thanks
