### ISSUE TITLE
Create TwoFactorLoginResponse contract and binding

### ISSUE THREAD

**Issue by snapey** [laravel/fortify#31]
We can conditionally redirect the user to different routes based on user attributes by creating a custom `LoginResponse` and binding our own response instead of the Fortify response.

Can we have the same for the `TwoFactorLoginResponse` so that this can be replaced also?

**Comment by driesvints** [comment]
Can you be a bit more specific at what you want to do?

**Comment by snapey** [comment]
Hi.  I wrote up a piece that explains how to substitute the LoginResponse so that projects can include some branching logic in the login process to redirect the user to a route according to their role (for instance).

It has been pointed out to me that this does not work if you use two-factor authentication.

The problem is that there is no contract for `TwoFactorLoginresponse` and the TwoFactorLoginResponse is not bound into the container and therefore cannot be swapped out.

( see https://talltips.novate.co.uk/laravel/laravel-8-conditional-login-redirects )

**Comment by assoft** [comment]
> Hi. I wrote up a piece that explains how to substitute the LoginResponse so that projects can include some branching logic in the login process to redirect the user to a route according to their role (for instance).
> 
> It has been pointed out to me that this does not work if you use two-factor authentication.
> 
> The problem is that there is no contract for `TwoFactorLoginresponse` and the TwoFactorLoginResponse is not bound into the container and therefore cannot be swapped out.
> 
> ( see https://talltips.novate.co.uk/laravel/laravel-8-conditional-login-redirects )
> 
> I could try a PR ?

Yes we want this. Please add the feature.

**Comment by driesvints** [comment]
@snapey yeah just try a pr, thanks.

**Comment by nicolailebek** [comment]
I don't know why you are binding the Login Response Class in Jetstreams Service Provider...

Here's what I did. Works for both TwoFactorLogin and vanilla login:

Create "LoginResponse.php" in "app/Http/Responses"

```
<?php

namespace App\Http\Responses;

use Laravel\Fortify\Contracts\LoginResponse as LoginResponseContract;

class LoginResponse implements LoginResponseContract
{
    /**
     * Create an HTTP response that represents the object.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function toResponse($request)
    {
        $role = \Auth::user()->role;

        if ($request->wantsJson()) {
            return response()->json(['two_factor' => false]);
        }

        switch ($role) {
            case 'admin':
                return redirect()->intended(config('fortify.home'));
            case 'host':
                return redirect()->intended('/host/dashboard');
            default:
                return redirect('/');
        }
    }
}
```

Create "TwoFactorLoginResponse.php" in "app/Http/Responses"

```
<?php

namespace App\Http\Responses;

use Laravel\Fortify\Contracts\TwoFactorLoginResponse as TwoFactorLoginResponseContract;

class TwoFactorLoginResponse implements TwoFactorLoginResponseContract
{
    /**
     * Create an HTTP response that represents the object.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function toResponse($request)
    {
        $role = \Auth::user()->role;

        if ($request->wantsJson()) {
            return response('', 204);
        }

        switch ($role) {
            case 'admin':
                return redirect()->intended(config('fortify.home'));
            case 'host':
                return redirect()->intended('/host/dashboard');
            default:
                return redirect('/');
        }
    }
}
```

Now register the response bindings in 'app\Providers\FortifyServiceProvider.php'

```
<?php

namespace App\Providers;

use Illuminate\Support\Facades\Route;
use App\Actions\Fortify\CreateNewUser;
use App\Actions\Fortify\ResetUserPassword;
use App\Actions\Fortify\UpdateUserPassword;
use App\Actions\Fortify\UpdateUserProfileInformation;
use Illuminate\Support\ServiceProvider;
use Laravel\Fortify\Fortify;
use Laravel\Fortify\Contracts\LoginResponse as LoginResponseContract;
use Laravel\Fortify\Contracts\TwoFactorLoginResponse as TwoFactorLoginResponseContract;
use App\Http\Responses\LoginResponse;
use App\Http\Responses\TwoFactorLoginResponse;

class FortifyServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        $this->registerResponseBindings();
    }

    /**
     * Register the response bindings.
     *
     * @return void
     */
    protected function registerResponseBindings()
    {
        $this->app->singleton(LoginResponseContract::class, LoginResponse::class);
        $this->app->singleton(TwoFactorLoginResponseContract::class, TwoFactorLoginResponse::class);
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {        
        Fortify::createUsersUsing(CreateNewUser::class);
        Fortify::updateUserProfileInformationUsing(UpdateUserProfileInformation::class);
        Fortify::updateUserPasswordsUsing(UpdateUserPassword::class);
        Fortify::resetUserPasswordsUsing(ResetUserPassword::class);
    }
}
```
