### ISSUE TITLE
Incomplete options array in config stub file

### ISSUE THREAD

**Issue by dmanva** [laravel/fortify#311]
- Fortify Version: 1.8.1
- Laravel Version: 8.56.0
- PHP Version: 7.4.14

### Description:
Config file 'fortify.php' was enhanced with 'redirects' array when redirection customization was added in #298. But Fortify only publishes config file from 'stubs' folder and that file doesn't contain new 'redirects' array, therefore redirects are not customizable "out of the box".

**Comment by driesvints** [comment]
You can just add the same redirects key and array to your published file and it'll work.
