### ISSUE TITLE
Add route suffix name into fortify routes

### ISSUE THREAD

**Issue by ousid** [laravel/fortify#314]
- Laravel: `v8.45`
- Fortify: `v1.6.1`
- PHP:  `8.0.10`

### Description
When I'm working on a project using Jetstream and fortify for authentication scaffolding, I faced a situation to ignore the default routes and create custom routes just for adding suffix for the `route names`, I think it would be a better idea to add `as` option on the route configuration and set it to null as the `domain` option.

### Steps to Reproduce
Sometimes we need to check if the route belongs to the `authentication routes` or a normal route to make certain operations (such as hide the `navbar` or something). So, instead of let's say

```blade
@if(! request()->routeIs('login', 'register', '...')
   Show navbar
@endif
```

We can just do this

```blade
@if(! request()->routeIs('auth.*'))
   show navbar
@endif
```

### The Solution
The solution actually is pretty simple, we need to add the `as` option into `configureRoutes` inside `fortifyServiceProvider` like this:

```diff
    protected function configureRoutes()
    {
        if (Fortify::$registersRoutes) {
            Route::group([
                'namespace' => 'Laravel\Fortify\Http\Controllers',
+                'as'  => config('fortify.route_suffix', null),
                'domain' => config('fortify.domain', null),
                'prefix' => config('fortify.prefix'),
            ], function () {
                $this->loadRoutesFrom(__DIR__.'/../routes/routes.php');
            });
        }
    }
```

and adding into `stubs/fortify.php` the following:

```diff
    'prefix' => '',
    'domain' => 'auth.' . config('app.url'),
+   'route_suffix'  => null,
```

I hope this make sense, and if it is, I can make a PR for it.

**Comment by driesvints** [comment]
Seems like your PR was rejected, sorry.
