### ISSUE TITLE
Can /login and /register routes response with user object after request success?

### ISSUE THREAD

**Issue by guoyunhe** [laravel/fortify#326]
In SPA, we need to get the user object to update navbar content, showing user name/avatar and hide login/register links. If `/login` and `/register` can response with user object, the UI update can be faster, than send another request for the user object.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
