### ISSUE TITLE
Changing email with email verification on should not immediately update the email

### ISSUE THREAD

**Issue by lsmith77** [laravel/fortify#331]
I am using Jetstream with emailVerification enabled on Fortify. If I change my email, the change takes effect immediately. This has several drawbacks:

1) If there is a typo, I have effectively locked myself out of my account.
2) Any other logic that depends on the users email now already sees the new unverified email which may allow people to spoof having a different email than they actually have, the very thing email verification was supposed to prevent.

As such it would make sense to store the new email separately and only make the change once the new email has been verified. This also means that until the verification the old email can be used for login or any other action, ensuring the user is not locked out of their account. That being said, Jetstream should also provide for a way to then cancel the email change.

**Comment by driesvints** [comment]
We've had several requests for this before. This has been the way it has always worked for the past few years on Jetstream and older scaffolds/Laravel core. I don't think we're going to change anything ourself here sorry.

That doesn't mean that we don't understand where you're coming from. But since it's been like this for so long, we won't be changing this.

**Comment by lsmith77** [comment]
OK thanks for the quick response.
One small clarification question:
So it does indeed mean that users can lock themselves out of their account and this cannot even be fixed via impersonation, since in that situation one would also no longer be able to edit the profile.

Meaning *if* this happens one needs some other way to edit the user's email (some custom UI or direct DB access).

**Comment by driesvints** [comment]
Or contact customer support.

**Comment by driesvints** [comment]
FYI: I added this to our backlog to maybe check into one day. No promises that it'll ever land. Thanks for the suggestion though!

**Comment by lsmith77** [comment]
OK cool.

Would working on a PR help facilitate prioritization? Or better stay put until it magically appears? ;)

**Comment by driesvints** [comment]
You can always attempt a PR to see if Taylor would accept that yeah.

**Comment by jimmays** [comment]
This is exactly my issue.  Has anyone implemented this or had experience with a workaround?
