### ISSUE TITLE
Laravel fortify authenticateUsing

### ISSUE THREAD

**Issue by GitzJoey** [laravel/fortify#337]
hi, i'm using laravel fortify and using feature of authenticateUsing coz i want to apply some custom Rules on the password field like so
```
Fortify::authenticateUsing(function (Request $request) {
        $request->validate([
            'password' => new mustResetPassword($request['email'])
        ]);

        return User::where('email', $request->email)->first();
    });
```

the problem is, i just realize that the standard rules is being ignored (eg, the required rules for the email fields). This because the based on the [source code](https://github.com/laravel/fortify/blob/2e084ad87ec52db136314f83ba4a1e45ce8ce311/src/Actions/AttemptToAuthenticate.php#L47) it return the callback without executing the standard rules

is there anyway to keep applying the default rules of authenticateUsing, and add a custom rules like my case?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by GitzJoey** [comment]
Hi @driesvints 
i think you misunderstood (maybe how i explain also wrong)
the issue is fortify::authenticateUsing is replacing or ignoring the default validation of fortify (shown in this [sourcecode](https://github.com/laravel/fortify/blob/2e084ad87ec52db136314f83ba4a1e45ce8ce311/src/Actions/AttemptToAuthenticate.php#L47)
my scenario is actually i just want to add another validation rules, rather than just replacing the authenticateUsing

just fyi i already tried to discuss in all channel u mention above, but no reply, hence i'm tried here

**Comment by driesvints** [comment]
@GitzJoey it's best that if you want to change anything here that you attempt a PR. Thanks
