### ISSUE TITLE
Confirmable 2FA Database migration when upgrading

### ISSUE THREAD

**Issue by ChrisRiddell** [laravel/fortify#364]
- Fortify Version: 1.11.1
- Laravel Version: 9.2.0
- PHP Version: 8.1.2
- Database Driver & Version:

### Description:
Upgrading fortify from 1.10.2 to 1.11.x you don't get the new columns in the database for the Confirmable 2FA https://github.com/laravel/fortify/pull/358 as they are not published for database migration. The new columns where added to the existing migration file not as a new file.

Or is this because the documentation for the Confirmable 2FA has not been added yet and a note saying if upgrading from 1.10.x to 1.11.x you need to create your own migration for the columns?

**Comment by driesvints** [comment]
This is intended, you'll have to manually create these in a new migration if you enable the feature.
