### ISSUE TITLE
Missing route name for password.confirm without enabled views

### ISSUE THREAD

**Issue by Frozire** [laravel/fortify#367]
Fortify Version: any
Laravel Version: any
PHP Version: any

### Description:
If you implement fortify without views, you have to hardcode the `password.confirm` route because no name is defined. 

https://github.com/laravel/fortify/blob/b2de125809a742acf08bc6bcbe8f90f8ae92df29/routes/routes.php#L120-L121

If you have views enabled, you are saved because a get route is defined with the same route.

https://github.com/laravel/fortify/blob/b2de125809a742acf08bc6bcbe8f90f8ae92df29/routes/routes.php#L110-L114

I am not sure of a good way to fix this, if you give this route a name, it will break existing implementations; a solution might be to do something like the following until a major version can be released to clean it up.

```php
if ($enableViews) {
    Route::get('/user/confirm-password', [ConfirmablePasswordController::class, 'show'])
        ->middleware([config('fortify.auth_middleware', 'auth').':'.config('fortify.guard')])
        ->name('password.confirm');

    Route::post('/user/confirm-password', [ConfirmablePasswordController::class, 'store'])
        ->middleware([config('fortify.auth_middleware', 'auth').':'.config('fortify.guard')]);
} else {
    Route::post('/user/confirm-password', [ConfirmablePasswordController::class, 'store'])
        ->middleware([config('fortify.auth_middleware', 'auth').':'.config('fortify.guard')])
        ->name('password.confirm');
}
```

While removing the code here

https://github.com/laravel/fortify/blob/b2de125809a742acf08bc6bcbe8f90f8ae92df29/routes/routes.php#L120-L121

**Comment by driesvints** [comment]
The get route already has the name defined. It's the same url. I'm not sure I see the issue.

**Comment by Frozire** [comment]
Unless you are using views the get route never gets defined.
