### ISSUE TITLE
password confirmation missing in verification

### ISSUE THREAD

**Issue by ddjikic** [laravel/fortify#370]
https://github.com/laravel/fortify/blob/87ba7ba8ded14766c724adb6e0055a1020680e20/src/Http/Controllers/NewPasswordController.php#L57

I think request validation should have validation for password confirmation.
currentli it  is :
` 'password' => 'required',`
and should be 
` 'password' => 'required|confirmed',`

**Comment by driesvints** [comment]
I don't think this is necessary.
