### ISSUE TITLE
Not having route named 'login' causes crash

### ISSUE THREAD

**Issue by JanMisker** [laravel/fortify#375]
I have a setup in which I want to group all fortify stuff under the `admin.` route prefix. So I don't have a route named `login`. In the config of fortify I have set up a redirect
```
    "redirects" => [
        "password-reset" => "/admin/login",
    ],
```
However I get an exception because `route('login')` is still called, it is the default fallback of the password-reset redirect. 
https://github.com/laravel/fortify/blob/b9cb52ec4a00500a80bcd2839c9a228958e7d3d9/src/Http/Responses/PasswordResetResponse.php#L39
I suppose it makes sense to provide that as default, but it's a bit of a pity I'd have to declare that route when I will never use it.

**Comment by driesvints** [comment]
I guess atm there's no easy way around this. Maybe we can add a new argument to the method in the next Fortify major version so you can define the fallback route's name. Feel free to attempt a PR for that, thanks.
