### ISSUE TITLE
Queue email verification feature

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/fortify#377]
I need to be able to queue the email verification email that's sent to the user upon registration to ensure that my front-end SPA remains as fast as possible. I came across [this](https://github.com/laravel/fortify/issues/287) from a while ago and wondered how can I achieve the queuing of the email verification and how I can change the queue that it's pushed onto, I don't just want it to be on the `default` queue.

I don't want to "hack" fortify, I'd much rather like Fortify to add this feature.

**Comment by driesvints** [comment]
As said on the other issue, it's best that you attempt a PR. Thanks
