### ISSUE TITLE
Define "illuminate/*" dependency requirement

### ISSUE THREAD

**Issue by klimov-paul** [laravel/fortify#38]
It is hard to tell whether this is intentional or not, but [composer.json](https://github.com/laravel/fortify/blob/1.x/composer.json#L16-L21) of this library does not contain any "illuminate/*" library constrait at all.

This might be flexible of course, but it is hard to determine, which Laravel version can match the particular version of this library.

I suggest the following line should be added to the `composer.json`:

```
{
    ...
    "require": {
        "illuminate/support": "^7.0 || ^8.0",
        ...
    }
}
```

**Comment by driesvints** [comment]
That's because it's meant to be used in conjunction with Jetstream. But feel free to pr those dependencies.
