### ISSUE TITLE
Route [login] is not defined with email verification

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/fortify#382]
- Fortify Version: 1.12.0
- Laravel Version: 8.83.5
- PHP Version: 7.4
- Database Driver & Version: SQL

### Description:

I'm using Laravel Fortify's login and email verification features, a customer has reached out to me today saying they're getting a 500 error, as it turns out, not every customer does, but when viewing the app with debug turned on, I get the error:

> Symfony\Component\Routing\Exception\RouteNotFoundException
Route [login] not defined.

I get this when loading up the `email/verify` route. When I run a `route:list` I do see that `login` is listed from Fortify, so not sure why it would throw this error.

How can I resolve?

**Comment by driesvints** [comment]
I asked you quite a few times now to stop posting support questions on our issue trackers so please stop doing this.

**Comment by sts-ryan-holton** [comment]
This isn't a support question this is a bug.
