### ISSUE TITLE
Update two_factor_confirmed_at after successful prompt 

### ISSUE THREAD

**Issue by Silver343** [laravel/fortify#386]
HI,

My app needs to know the last time a TOPT prompt was successful, I wasn't sure if there was an event for it but I couldn't see one, if there isn't one I was thinking of submitting a PR which would update the users two_factor_confirmed_at after each successful prompt. But I wanted to check there wasn't already a way to get a timestamp.

Thanks.

**Comment by driesvints** [comment]
I don't think so. Feel free to attempt a PR 👍
