### ISSUE TITLE
Return a Responsable interface instance instead of pre-defined JsonResponse or RedirectResponse on update profile action

### ISSUE THREAD

**Issue by a-bashtannik** [laravel/fortify#388]
`ProfileInformationController::update` [can return 2 kinds of response instances](https://github.com/laravel/fortify/blob/1.x/src/Http/Controllers/ProfileInformationController.php#L24) only: `JsonResponse` or `RedirectResponse`. 

In the same time, `RegisteredUserController::store` [allows customization by returning](https://github.com/laravel/fortify/blob/1.x/src/Http/Controllers/RegisteredUserController.php#L58) resolved `RegisterResponse` which behavior can be redefined somewhere in the app's service providers by developers via IoC. 

Same approach applies in other controllers like `PasswordResetLinkController` or `NewPasswordController`. 

I suggest changing the behavior of `ProfileInformationController::update`, extracting the method implementation, and returning resolved `UpdateProfileResponse` instance, like in other examples, allowing developers customizing the response if need. 

I'm ready to create a pull request.

**Comment by driesvints** [comment]
Sure, feel free to attempt a PR.
