### ISSUE TITLE
Prefixing routes url

### ISSUE THREAD

**Issue by mohamedsabil83** [laravel/fortify#40]
I localized my projects by prefix URL with a locale symbol. How I can do it with fortify to be like 'en/login', 'en/register', ... etc?

**Comment by wfern** [comment]
As Taylor said in another issue, you can disable the routes via Fortify::ignoreRoutes() and then copy the routes into a file in your own application and configure the locale in routes as in the [documentation](https://laravel.com/docs/8.x/localization#configuring-the-locale).

**Comment by driesvints** [comment]
See the answer above, thanks.

**Comment by hairmenu** [comment]
Hi

It sounds a bad practice to copy the routes from the vendor in order to pre-fix the fortify routes. Any Official package should provide a valid localization option in my opinion.
