### ISSUE TITLE
Passwordless login with link and passphrase.

### ISSUE THREAD

**Issue by ProgrammerZ** [laravel/fortify#402]
I'm building myself a passwordless login on top of Fortify. Would it be useful to make a PR for this feature? 
I find passwordless login more user friendly and safer, at the same time not removing ability to set the password.

The workflow is currently as follows:
- user enters email
- email/request that contains link with single-use token and passphrase is sent. 

- tokens are saved in separate table, 
- tokens have expiration and are single-use
- email/request also contains 6-8 numeric or 3-4 word passphrase for manual entry. 
(optional)
- user can have X amount of tokens ( I found that a lot of user request links 2-3 times if email don't arrive instantly and are confused why they don't work ). After login all tokens are invalidated for user. 

Let me know if there is interest in this and if there are other requirements.

**Comment by driesvints** [comment]
Hi there. Right now, we don't have any plans for this, sorry. Thanks
