### ISSUE TITLE
Don't keep promoting for 2FA code, allow window customisation

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/fortify#403]
I'm using 2FA in Fortify. I'd like to be able to customise how long after a successful log in that a 2FA code won't be requested again, for example, right now:

1. I log in
2. I'm prompted for my 2FA code
3. I enter it successfully, and am then logged in
4. I then manually log out after say two minutes
5. I go to log in again, and it prompts be for the 2FA code

Is there any chance, if set, I can effectively supress the requirement for a 2FA code within X minutes of a successful code, a bit like a "remember me" feature.

**Comment by driesvints** [comment]
Hey there. Right now we don't have any plans for this, sorry.
