### ISSUE TITLE
Multi Factor Authentication support

### ISSUE THREAD

**Issue by ProgrammerZ** [laravel/fortify#413]
I believe the package is lacking ability to set multiple 2FA options for the user. Although it's a huge help for devs to have TOTP out of the box, but I can't remember any website that have only TOTP.

The package would benefit a lot if it had native support for Multi Factor Authentication, so you can set your own implementation for 2FA via email, SMS or Fax. )

**Comment by driesvints** [comment]
Right now, we don't have any plans to add more, sorry.

**Comment by officialkidmax** [comment]
Still, there are no plans to add MFA yet?
