### ISSUE TITLE
in loginPipeline LoginRequest Customer customization

### ISSUE THREAD

**Issue by phpmac** [laravel/fortify#414]
<img width="1726" alt="截屏2022-10-21 23 56 00" src="https://user-images.githubusercontent.com/86544347/197238285-12c85777-99ee-4b21-bc2e-441dd21f7a43.png">
<img width="1349" alt="截屏2022-10-21 23 55 57" src="https://user-images.githubusercontent.com/86544347/197238295-4f0e42e2-138c-40bf-815a-428b899d0ae1.png">

I need to customize.

**Comment by driesvints** [comment]
Please attempt a PR if you want to add something here, thanks.
