### ISSUE TITLE
Fortify can't return Inertia Response

### ISSUE THREAD

**Issue by classjunky** [laravel/fortify#42]
- Fortify Version: 1.4.0
- Laravel Version: 8.4.0
- PHP Version: 7.4.3
- Database Driver & Version:

### Description:
```
TypeError
Argument 1 passed to Symfony\Component\HttpFoundation\Response::setContent() must be of the type string or null, object given, called in laravel\framework\src\Illuminate\Http\Response.php on line 65
```
I did some debugging, and basically when you return an Inertia response in a common controller `Illuminate\Routing\Router::toResponse()` receives Inertia\Response object where then it calls its own `toResponse()` to return `Illuminate\Http\Response` and all is good.

But, using:
```
Fortify::loginView(function () {
    return inertia('Auth/Login');
});
```
it fails to build the response because of the `SimpleViewResponse` and simply returns and `Inertia\Response` object instead of a string, hence the error above.

### Steps To Reproduce:
Configure Inertia, make a Vue component `resources/js/Pages/Auth/Login.vue` and in `FortifyServiceProvider::boot()` paste:
```
Fortify::loginView(function () {
    return inertia('Auth/Login');
});
```

**Comment by markbiek** [comment]
I came to leave this exact issue. Thanks @classjunky

**Comment by classjunky** [comment]
**UPDATE:**

Here's a quick fix:

```
Fortify::loginView(function (Request $request) {
    return inertia('Auth/Login')->toResponse($request);
});
```

@markbiek

**Comment by leo95batista** [comment]
I have the same problem, any official solution?

**Comment by classjunky** [comment]
@leo95batista The solution I provided above works just fine, you can see that on https://xp.amirrami.com.

Although I wish for solution since I, like most Laravel developers like to keep it simple.

**Comment by driesvints** [comment]
Feel free to pr, thanks.

**Comment by Shianchu** [comment]
Could you tell me how to config Inertia in FortifyServiceProvider?

**Comment by P-James** [comment]
This solution is causing  
`ErrorException
strpos() expects parameter 1 to be string, object given `

from `\vendor\laravel\framework\src\Illuminate\View\ViewName.php:17` 

for me

**Comment by emlazaroiii** [comment]
I wonder if this is what you're looking for... maybe this could help you or someone out there :)

### Using Inertia alone...

```
Fortify::loginView(function () {
    return Inertia::render('Auth/Login');
});
```

**OR**

### Using Ziggy with Inertia...

  ```
  Fortify::loginView(function () {
      return route('login');
  });
  ```
  
  Given that `route('login')` is declared as...

```
//routes/web.php

Route::get('login', [LoginController::class, 'create'])->name('login');
```

```
//Auth/LoginController.php

public function create(Request $request, Router $router)
{
    return Inertia::render('Auth/Login');
}
```
