### ISSUE TITLE
Laravel Fortify not triggering Two Factor Challenge 

### ISSUE THREAD

**Issue by umairge66** [laravel/fortify#430]
- Fortify Version: 9.43.0
- Laravel Version: 9.43.0
- PHP Version: 8.1.13
- Database Driver & Version: MySQL

### Description:
Hi,

I am using Fortify package in my application all the feature working fine Two factor also enabled I have checked the database also all the required fields are filled and I also have configured two-factor-challenge.blade.php. But for some reasons it not redirecting me to Two factor challenge instead it redirect back to login when I try to login.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
