### ISSUE TITLE
Laravel Fortify logoutOtherDevices not working in custom Laravel Application

### ISSUE THREAD

**Issue by umairge66** [laravel/fortify#431]
- Fortify Version: 1.14.0
- Laravel Version: 9.43.0
- PHP Version: 8.1.13
- Database Driver & Version:

### Description:
I don't know but I have searched all over the internet but I can't figure it out why Laravel Fortify logoutOtherDevices function not working. I need urgent help please don't tell that find you answer from that forums if you have a solution from any forum please mentioned it.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
