### ISSUE TITLE
Setup Key instead of a QR Code when authenticating with Google Auth APP

### ISSUE THREAD

**Issue by RichieMcMullen** [laravel/fortify#436]
Sorry if this already exists, but I cannot see any information on it whatsoever.

I was trying to activate two factor authentication for my laravel app on my mobile phone, the same phone that has my google authenticator app installed.

Obvioulsy I was unable to scan the QR code as I was using my phone. Would it not make sense to implement an alternative to providing the user with a QR code, maybe provide them with a numeric "Setup Key" and a QR code, to give them the option to scan via phone or simply copy paste the code into the authenticator app.

So, I'm proposing that a **Setup Key** and a **QR Code** is generated while enabling two factor auth using fortify.

**Comment by driesvints** [comment]
This is already done. A setup key is already generated alongside the QR code.

<img width="697" alt="Screenshot 2023-01-10 at 10 08 07" src="https://user-images.githubusercontent.com/594614/211508586-59df464d-dadd-417e-bcbb-ce9a87b4079e.png">

**Comment by RichieMcMullen** [comment]
Oh ok. Can you provide a link to where this is documented, I only seem to be getting the QR code. Is there an additional call required to output the setup key?

**Comment by driesvints** [comment]
You might have outdated stubs

**Comment by RichieMcMullen** [comment]
> You might have outdated stubs

How do I go about updatig them? Sorry, I'm not familiar with stubs.

**Comment by driesvints** [comment]
Sorry, didn't realize you weren't using Jetstream. Your set up key can be used like this: 

https://github.com/laravel/jetstream/blob/6f661f6355be719490107cc0dd8e424083af3ca9/stubs/livewire/resources/views/profile/two-factor-authentication-form.blade.php#L47

**Comment by RichieMcMullen** [comment]
@driesvints  Thats perfect. Appreciate the help with this, thank you.
