### ISSUE TITLE
Call to undefined getModel for Sanctum + Fortify with config.auth.providers.user.database

### ISSUE THREAD

**Issue by xizprodev** [laravel/fortify#437]
- Fortify Version: 1.16.0
- Laravel Version: 9.48.0
- Laravel Sanctum: 2.15.1
- PHP Version: 8.1.11
- Database Driver & Version: mysql  Ver 8.0.30-0ubuntu0.20.04.2 for Linux on x86_64

### Description:
Trying default Laravel authentication Sanctum + Fortify working excellent with Eloquent Model.
If i change the settings in config/auth/providers --> users.driver = database insteand of eloquent i receive the next error:
"Call to undefined method Illuminate\\Auth\\DatabaseUserProvider::getModel()"
vendor/laravel/fortify/src/Actions/RedirectIfTwoFactorAuthenticatable.php
line:89

### Steps To Reproduce:

- default laravel project with sanctum and fortify
- change config from auth for providers from eloquent to database.
 
```
     'providers' => [
        // 'users' => [
        //     'driver' => 'eloquent',
        //     'model' => App\Models\User::class,
        // ],

        'users' => [
            'driver' => 'database',
            'table' => 'users',
        ],
    ],
```

I created two pull requests that solve this problem. Those are my first contributions on a open source projects, so I'm sorry if I don't make it in the right way.

**Comment by driesvints** [comment]
Right now, fortify only supports eloquent models.

**Comment by xizprodev** [comment]
> Right now, fortify only supports eloquent models.

ok, but this is a limitation. why laravel supports both eloquent + database user drivers in documentation, but fortify supports only eloquent?
