### ISSUE TITLE
Password Rule implements deprecated Illuminate\Contracts\Validation\Rule

### ISSUE THREAD

**Issue by falko100** [laravel/fortify#440]
- Fortify Version: v1.16.0
- Laravel Version: v10.0.0
- PHP Version: 8.1
- Database Driver & Version: n.a.

### Description:
`\Laravel\Fortify\Rules\Password`
implements deprecated `Illuminate\Contracts\Validation\Rule`
instead of `Illuminate\Contracts\Validation\ValidationRule`

#### Edit:
I won't mind giving this a go for contributing. Do you have any example of how you do a test for the `Illuminate\Contracts\Validation\ValidationRule` ?

**Comment by falko100** [comment]
Would this be the way to go?
```php
$this->assertThrows(function () {
    validator(
        ['password' => 'secret'],
        ['password' => [new Password]],
    )->validate();
}, ValidationException::class, 'The password must be at least 8 characters.');
```

**Comment by driesvints** [comment]
I'm not sure myself. Maybe try discord to see if there's someone who can help you with the PR?
