### ISSUE TITLE
Class "App\Providers\FortifyServiceProvider" not found

### ISSUE THREAD

**Issue by prpanto** [laravel/fortify#445]
- Fortify Version: latest
- Laravel Version: latest
- PHP Version: 8.1
- Database Driver & Version: mysql  Ver 8.0.32-0ubuntu0.22.04.2 for Linux on x86_64 ((Ubuntu)) 

### Description:

On fresh laravel project try to install the fortify and error appeared FortifyServiceProvider not found.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
