### ISSUE TITLE
two_factor_comfirmed_at & two factor challenge not working

### ISSUE THREAD

**Issue by wizard2000** [laravel/fortify#453]
- Fortify Version: 1.16.0
- Laravel Version:10.1.0
- PHP Version: 8,1.0
- Database Driver & Version: Mariadb last version 

### Description:
when i try to disable two factor athentican, i get this error:
`
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'two_factor_confirmed_at' in 'field list' (Connection: mysql, SQL: update `users` set `two_factor_secret` = ?, `two_factor_recovery_codes` = ?, `two_factor_confirmed_at` = ?, `users`.`updated_at` = 2023-03-30 12:05:28 where `id` = 2)
`
also after enabling this feature the two factor challenge is not working at all and i returened to home route directly.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
