### ISSUE TITLE
Temporarily edit generated email verification URL for a user flow journey

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/fortify#455]
Hi, I have a sign-up journey in my project that needs to create a email verification link journey that redirects the user to a different url than the one defined in my config by default.

I'm using Laravel 10 and the newest Fortify version, my Laravel project is an API, so no views here, my front-end is an SPA.

Here's my `home` path _(presumably used for redirections)_

```php
/*
|--------------------------------------------------------------------------
| Home Path
|--------------------------------------------------------------------------
|
| Here you may configure the path where users will get redirected during
| authentication or password reset when the operations are successful
| and the user is authenticated. You are free to change this value.
|
*/

'home' => env('SPA_URL', 'https://example.com/account/domains/'),
```

It's then set in my `.env`

```
SPA_URL=http://localhost:3000/account/domains/
```

What I'd like to do, is when my user is created, I'm passing a boolean switch before user creation called `is_onboarding_journey`. How can I generate the email verification email that's sent that contains a redirection to a different page?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
