### ISSUE TITLE
Accept pull request for adding named route for two-factor auth challenge?

### ISSUE THREAD

**Issue by OliverGrimsley** [laravel/fortify#468]
Using Ziggy to publish routes.  Ziggy only pushes named routes to the front end.  There is no named route for POST two-factor challenge.  That code in Fortify is currently:

```php
Route::post(RoutePath::for('two-factor.login', '/two-factor-challenge'), [TwoFactorAuthenticatedSessionController::class, 'store'])
            ->middleware(array_filter([
                'guest:'.config('fortify.guard'),
                $twoFactorLimiter ? 'throttle:'.$twoFactorLimiter : null,
            ]));
```
As a work around, I have added the following to my local routes file:

```php
Route::post(RoutePath::for('two-factor.challenge', '/two-factor-challenge'), [TwoFactorAuthenticatedSessionController::class, 'store'])
    ->middleware(array_filter([
        'guest:' . config('fortify.guard'),
        $twoFactorLimiter ? 'throttle:' . $twoFactorLimiter : null,
    ]))->name('two-factor.challenge');
```

Was going to send a pull request to add this to Fortify, BUT . . . I am not sure if this would break anything for other users to change `RoutePath::for('two-factor.login'`... to `RoutePath::for('two-factor.challenge'...`?  I did not think so because (a) in current Fortify, this is not a NAMED route; and (b) the actual endpoint URL has not been changed.

Happy to send a pull request if this is ok.

**Comment by nunomaduro** [comment]
You can send a pull request, so Taylor Otwell can have the opportunity to understand your needs, and evaluate if your pull request will be breaking for existing users or not.
