### ISSUE TITLE
Fortify 

### ISSUE THREAD

**Issue by DenChai1** [laravel/fortify#475]
### Fortify Version

1.16.0

### Laravel Version

8.83.27

### PHP Version

7.4.33

### Description

I have a Laravel website and use Fortify for user email authentication. Some of my new users encounter a 403 Invalidate Signature error when they click on the verification email link from their phone (they use an iPhone). I tried to reproduce the error but couldn't. Can you please explain this problem? And any possible solutions? 

### Steps To Reproduce

I couldn't reproduce the error

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by DenChai1** [comment]
Thank you for your feedback. 
It's just that I haven't changed anything in the default Fortify/Laravel configuration and I was wondering if it was directly related to the Fortify/Laravel configuration.
