### ISSUE TITLE
The route name for registration is not declared.

### ISSUE THREAD

**Issue by artem3k** [laravel/fortify#477]
### Fortify Version

1.17.4

### Laravel Version

10.10

### PHP Version

8.2.3

### Description

If you disable view pages in the Fortify configuration, the Features::registration() route will not have a route name assigned to the /register URL.

    if (Features::enabled(Features::registration())) {
        if ($enableViews) {
            Route::get(RoutePath::for('register', '/register'), [RegisteredUserController::class, 'create'])
                ->middleware(['guest:'.config('fortify.guard')])
                ->name('register');
        }

        Route::post(RoutePath::for('register', '/register'), [RegisteredUserController::class, 'store'])
            ->middleware(['guest:'.config('fortify.guard')]);
    }

### Steps To Reproduce

  Features config
  
    'features' => [
        Features::registration(),
        ...
        ],
     views' => false,

**Comment by driesvints** [comment]
Thanks, can you send in a PR that switches the name to the POST route?
