### ISSUE TITLE
login limiter  doesn't  work  actually

### ISSUE THREAD

**Issue by marol1210** [laravel/fortify#483]
### Fortify Version

1.17.4

### Laravel Version

9.33.0

### PHP Version

8.1.4

### Description

fortify use name 'login' for limiter  in routes file ,  but  resolveMaxAttempts is 0 when ThrottleRequests's  function  handle  call.

### Steps To Reproduce

ThrottleRequests can't find 'login' limiter.   so  , what's  the function  about  'login' ?

```
    $limiter = config('fortify.limiters.login');
    $twoFactorLimiter = config('fortify.limiters.two-factor');
    $verificationLimiter = config('fortify.limiters.verification', '6,1');

    Route::post(RoutePath::for('login', '/login'), [AuthenticatedSessionController::class, 'store'])
        ->middleware(array_filter([
            'guest:'.config('fortify.guard'),
            $limiter ? 'throttle:'.$limiter : null,
        ]));
```

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
