### ISSUE TITLE
Integrate Precognition Into Fortify Route

### ISSUE THREAD

**Issue by GitzJoey** [laravel/fortify#488]
```
    Route::post(RoutePath::for('login', '/login'), [AuthenticatedSessionController::class, 'store'])
        ->middleware(array_filter([
            'guest:'.config('fortify.guard'),
            $limiter ? 'throttle:'.$limiter : null,
        ]));
```
this route in fortify, it would be better if there's a way to add precognition middleware, so precognition can be used also in fortify
understand that we can override this route easily, but it would be nicer if laravel ecosystem is filling each others gap.

**Comment by driesvints** [comment]
Thanks. Right now we have no plans for this sorry.
