### ISSUE TITLE
Without override the PasswordResetLinkController@store we cannot add reCAPTCHA 

### ISSUE THREAD

**Issue by fabiomlferreira** [laravel/fortify#495]
I am currently integrating reCAPTCHA into various guest forms (login, registration, and forgot-password) using Jetstream and encountered a limitation regarding validation rule customization in Fortify.

In order to validate the reCAPTCHA token, I need to add a new validation rule to the existing rules in Fortify. While I can create a custom controller and route to override the store method in PasswordResetLinkController, this approach seems to be against the recommended practice of utilizing Actions for customization in Fortify/Jetstream.

It would be immensely beneficial to have a straightforward way to customize validation rules for Fortify's form requests without resorting to overriding controllers or methods. This could potentially be achieved by allowing developers to define additional validation rules through Actions or another extensible approach.

Thank you for considering this enhancement. I believe it would provide a smoother and more intuitive customization experience for developers using Fortify and Jetstream.

**Comment by driesvints** [comment]
Hi there, while I realize this would indeed be beneficial, right now we don't have plans to work on this ourselves, sorry. I realize overwriting the controller is cumbersome but for now it'll be your best option. Introducing a new system to overwrite validation rules could prove difficult to come up with.

**Comment by tarun-rayzon** [comment]
@fabiomlferreira  I found the solution.
