### ISSUE TITLE
Password reset exposes if an account exists

### ISSUE THREAD

**Issue by bkilshaw** [laravel/fortify#50]
### Description:
When performing a password reset, users enter an email address and the request gets posted to /forgot-password. If someone enters an email that doesn't exist, Fortify returns an error. If the email does exist, it returns a status message that the email has been sent.

This exposes whether or not an account exists on the system which provides an attacker with information. They can now target that user/email address directly with phishing or social engineering attempts.

Best practice would be to skip returning any errors and to always notify users that "An email has been sent to taylor@laravel.com with password reset instructions."

**Comment by driesvints** [comment]
If you attempt to register an account on any app with an email address that exists you get the same result.

**Comment by taylorotwell** [comment]
I'm not concerned about this:

<img width="676" alt="image" src="https://user-images.githubusercontent.com/463230/93616298-2d638c80-f99a-11ea-89cf-aaeda3964056.png">

**Comment by bkilshaw** [comment]
Fair enough -- in my opinion though leaking that information does depend on the nature of the site. Twitter, Youtube, Facebook, might not be a huge deal. You could actually probably assume a good chunk of people already do have accounts on those sites. With a package like Fortify though you don't always know what people are building with it and in some cases leaking that information could be much more personal;  imagine if someone made like... "living-with-aids.com".

I get that as developers it's up to us to know and follow best practices, but it would also be nice for a package like Fortify to follow all and advocate the best practices as well.

**Comment by ali-alharthi** [comment]
@bkilshaw I totally understand this.
I build apps that are used by military/government contractors. So I always respond with a success message that looks like the following: 
> If an account exists with the given email address an email with a password reset link should have been sent.

You can achieve this in Fortify:
1. Make sure that you are using your own routes and not Fortify's.
2. Extend the store method on the `PasswordResetLinkController` to return the following:
```
        return $status == Password::RESET_LINK_SENT
                    ? app(SuccessfulPasswordResetLinkRequestResponse::class, ['status' => $status])
                    : app(SuccessfulPasswordResetLinkRequestResponse::class, ['status' => $status]);
```
Or simply:
```return app(SuccessfulPasswordResetLinkRequestResponse::class, ['status' => $status]);```

And that should do the trick! I used to do the same with laravel/ui.

Like @taylorotwell said it is not a big deal but for some people like us it is! However, the majority don't mind leaking such information. Therefore, If you have a specific use case just extend (that is why I love Laravel).

**Comment by bkilshaw** [comment]
Thanks @ali-alharthi -- that's a much more thorough way to handle it compared to what I hacked together originally!

Still holding out that they eventually update Fortify to follow the best practices out of the box, but it's nice having the ability to easily make those changes!

**Comment by johanvanhelden** [comment]
I'm hoping for a way to easily do this without copy-pasting the Fortify routes and overriding the controller method. It makes updating a bit less easy.

Just a hook to override the response would be great and makes updating very easy.

**Comment by lukasz-shadowapi** [comment]
Using Twitter as grounds to dismiss a security issue is just ignorant. 

Surely you're not comparing every website built with this to Twitter? Seems very detached from reality. You honestly cannot expect every small website to have the level of defence that twitter has against user enumeration spams.

In fact, as it stands you can spam this controller as long as you want and get all the emails/usernames you want even if it takes 3 months. 

What about the systems that don't allow user registration and they have to be created by an admin? 

This was a security issue 10 years ago. I really don't get why this is still an issue today.

**Comment by johanvanhelden** [comment]
My suggestion would be to add an option to specify our own response, with a value being available to us whether it was successful or not and the form input. This allows for maximum flexibility. So we could simply redirect->back with a generic message or show a detailed message.

In my case, I would send a message back like: "If an account exists for 'taylor@laravel.com', you will have received a confirmation mail."
