### ISSUE TITLE
Paths override with dot in route name does not work

### ISSUE THREAD

**Issue by sebj54** [laravel/fortify#500]
### Fortify Version

1.18.0

### Laravel Version

10.16.2

### PHP Version

8.2.8

### Description

When there is a dot in the route name, it is not possible to customize route paths the way it is described in the default config: https://github.com/laravel/fortify/blob/b5743b04b07f5420e85665d978d15c7728e8dc03/config/fortify.php#L20-L42

`RoutePath` will get the config value for a given path with the `config()` function (see below). Because of that, dots are representing config paths and each item before a dot is an array.

https://github.com/laravel/fortify/blob/b5743b04b07f5420e85665d978d15c7728e8dc03/src/RoutePath.php#L16

Instead, route paths should be declared with arrays actually: 

```php
return [
    'paths' => [
        'login' => null,
        'logout' => null,
        'password' => [
            'request' => null,
            'reset' => null,
            'email' => null,
            'update' => null,
            'confirm' => null,
            'confirmation' => null,
        ],
        'register' => null,
        'verification' => [
            'notice' => null,
            'verify' => null,
            'send' => null,
        ],
        'user-profile-information' => [
            'update' => null,
        ],
        'user-password' => [
            'update' => null,
        ],
        'two-factor' => [
            'login' => null,
            'enable' => null,
            'confirm' => null,
            'disable' => null,
            'qr-code' => null,
            'secret-key' => null,
            'recovery-codes' => null,
        ]
    ],
];
```

The easiest fix is to change the default config object (and maybe the docs). But I think it would be more relevant if `RoutePath::for()` would get the whole paths array with `config('fortify.paths')` and then get the custom path if it exists.

### Steps To Reproduce

Define a custom path for a route with a dot (for instance `two-factor.login`):

```php
// config.fortify.php
return [
    'paths' => [
        'two-factor.login' => '/custom/path',
    ],
];
```

Then get route list with `php artisan route:list`

👉 The custom path is not taken in account

**Comment by driesvints** [comment]
I think your suggestion to update the config to nested arrays is the right one. Can you PR this?

**Comment by sebj54** [comment]
Sure! :) It's done with #501
