### ISSUE TITLE
Fortify http request methods for routes requiring multipart/form-data

### ISSUE THREAD

**Issue by stradox4u** [laravel/fortify#502]
- I find that sending a formData object from client-side Javascript to the Fortify endpoints whose request method isn't POST fails, as I think PHP only accepts formData in a POST request. I ran into this issue while building out the client side for the `user/profile-information` endpoint which expects a PUT request.
- Would it be possible to add an option in the exposed fortify config to coerce all formData expecting endpoints to expect POST requests?
- I realize that this would not be semantically correct, but I think it might be worth allowing the user to knowingly break this for a little easier DX.
- My solution was to write out my own POST route, which got it to work.
- I'd be happy to work on this myself, if it is an option.

**Comment by driesvints** [comment]
We don't have any plans for this sorry.
