### ISSUE TITLE
Provide "Don't ask me again on this computer" feature

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/fortify#508]
Hi, I use Laravel Fortify v1 in my application. I know that Laravel has a "Remember me" feature, but, I feel that the "Don't ask me again on this computer" feature for 2FA should be separate. Is there any chance of adding such a feature?

**Comment by driesvints** [comment]
Right now we don't have any plans for this, sorry

**Comment by danmatthews** [comment]
@driesvints if I did a pull request for this, would you consider it? 

I realise it crosses a lot of boundaries like with Jetstream etc, but it's something i think would be super-handy.

**Comment by driesvints** [comment]
I can’t promise it’ll get accepted but you can always try 👍

**Comment by LWlook** [comment]
This would really be a helpful feature. Most users of us won't use 2FA bacause they have to type it every time, even on the same browser/device.
