### ISSUE TITLE
No error message on expired token

### ISSUE THREAD

**Issue by szepeviktor** [laravel/fortify#516]
### Fortify Version

1.19.0

### Laravel Version

10.34.2

### PHP Version

8.2.13

### Database Driver & Version

MariaDB 10.3.39 on Debian buster amd64

### Description

Requesting a new password reset makes the token in the previous one expired.
Clicking on that expired link loads the password reset form but there is no error message.

The "token expired" error message appears only when the user submits the form.
Inspired by @iamgergo

### Steps To Reproduce

1. Request password reset
2. Request password reset again
3. Click the link in the first email (that contains the expired token)

**Comment by driesvints** [comment]
We'd appreciate a PR to make this more clear, thanks.

**Comment by szepeviktor** [comment]
@driesvints Could you ensure me that a PR displaying an error message will get merged?

**Comment by driesvints** [comment]
No. Everything depends on the code involved and the complexity. If you really need this and want to be sure, you can always fork the library.
