### ISSUE TITLE
A proposal for Fortify 2.0

### ISSUE THREAD

**Issue by x7ryan** [laravel/fortify#521]
This is kind of a bold idea. A reinventing, a rewrite of Fortify. Since Fortify has been released [Passkeys](https://www.passkeys.com/) have come out and are growing in popularity. Many of the Issues and PR's submitted have asked for additional forms of 2FA, which Taylor (understandably) does not want to take on the maintenance burden of supporting. I too find myself wanting more from Fortify and from the authentication mechanisms of Laravel. We in the Laravel Ecosystem are lucky to have such good baked in auth support and not have to rely on third party auth solutions, but there is so much more we could add.

So here if my vision for Fortify 2. Fortify 2 would register an auth guard that we can opt into using in our Laravel apps. Fortify would be just a shell or a framework if you will for composing complex authentication flows. Everything would be implemented as a Fortify Driver which would follow a standard interface. Each of these drivers would be responsible for managing a form of authentication. Fortify may simply just ship with the equivalent of what 1.x  has (a password driver and a TOTP driver) any other drivers would be provided by the community as third party packages that could plug into Fortify if installed.

Fortify would be configured with essentially two arrays, a "primary_drivers" array and a "secondary_drivers" array. Each user must use one of the primary drivers, but may optionally choose to setup one of the secondary drivers too. The fortify guard would only consider the user authenticated once they have been verify via the primary driver (and if the user has enabled it on their account the secondary driver). I imagine the default configuration would be a "Password Driver" as the primary driver and a "TOTP Driver" as a secondary driver. But there is a plethora of additional driver ideas the community could build such as:

* Passkey/Webauthn Driver
* Magic Link Driver
* Socialite Driver
* Email or SMS code driver

Each developer could choose which drivers to install with Fortify and which to enable as a choice a user may choose as their Primary authentication form, as well and which may serve as a second factor that a user could opt into.

At least that's my vision for the future of authentication with Laravel and Fortify. I would love to get some feedback from the community, but especially from Taylor and the Laravel team if this is something that they would even have a desire to consider.

**Comment by crynobone** [comment]
This issue board is for tracking bugs and feature requests. Please direct general discussion to https://github.com/laravel/framework/discussions

**Comment by x7ryan** [comment]
Umm this is a feature request for fortify not a general discussion for the framework. I think you made a mistake.

**Comment by crynobone** [comment]
Sorry, corrected my mistake above. There's a categories in Laravel Framework discussion for this: https://github.com/laravel/framework/discussions/categories/ideas

**Comment by x7ryan** [comment]
Ok but this is a feature request for fortify not the framework.

I guess I'm just going to take this as a no and build my own then.
