### ISSUE TITLE
Used password reset link still valid to change password again

### ISSUE THREAD

**Issue by umairge66** [laravel/fortify#522]
### Fortify Version

1.20.1

### Laravel Version

10.44

### PHP Version

8.2.4

### Database Driver & Version

Database client version: libmysql - mysqlnd 8.2.4

### Description

Hope you doing well,

Using fortify for 1 year for my differents projects. I think I never noticed this thing but today I noticed that when I request to reset my password I got email with reset link. After clicking on link I am able to change password successfully. But after changing password I am still able to used that link again to change the password. I think this is a bug or may not be please let me know.

I shall be very thankful to you.

Regards,
Umair Saeed

### Steps To Reproduce

1. Send reset password request.
2. Open reset password link from email and change password.
3. Then again open then same reset link and you still can change the password

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
