### ISSUE TITLE
RegisterViewResponse is not instantiable.

### ISSUE THREAD

**Issue by sv3tli0** [laravel/fortify#526]
### Fortify Version

1.21.0

### Laravel Version

11.0.6

### PHP Version

8.3.3

### Database Driver & Version

SQLite

### Description

After clean installation of laravel + laravel/fortify. 

Moving to the Register page gives an error: 
<img width="1477" alt="image" src="https://github.com/laravel/fortify/assets/1014039/6c20bdab-e01c-471f-85d0-ed0b6b48970b">

### Steps To Reproduce

```
laravel new TestFortify
composer require laravel/fortify
php artisan fortify:install
php artisan migrate
php artisan serve
```

Go To: `/register`

**Comment by driesvints** [comment]
That's normal. If you use Fortify without a starter kit like Breeze and Jetstream you're responsible to implement these contracts and views yourself. See https://laravel.com/docs/11.x/fortify#registration and other sections of the docs.

**Comment by sv3tli0** [comment]
👍🏻 
Just would be logical to have some graceful error on what is missing instead of leaving it to the generic Laravel Container errors.
Thanks
