### ISSUE TITLE
Password customization rule

### ISSUE THREAD

**Issue by joval-sv** [laravel/fortify#53]
I am new to fortify, but would like to require a password contain at least one of a configurable set of symbols like` '#', '$', '%', '_', '-','+'`, etc.

I was looking at the source, and there is a Fortify Rule named Password, and it's missing the logic I want/need. I could write another Fortify Rule to take this into account, but it would nice to have it out of the box in order to create really strong passwords.

Also, is there someplace special where these rules ought to go, specially if we want to tweak the current ruleset?

**Comment by irsyadadl** [comment]
Why do you make it as fortify issue? Fortify just backend for laravel authentication. You ask for validation.

**Comment by driesvints** [comment]
https://jetstream.laravel.com/1.x/features/authentication.html#password-validation-rules
