### ISSUE TITLE
Redirect after register oder login doesn't work with 'home' => '/profil' in fortify-config

### ISSUE THREAD

**Issue by kakojak** [laravel/fortify#538]
### Fortify Version

1.21.2

### Laravel Version

11.6.0

### PHP Version

8.2

### Database Driver & Version

MySQL

### Description

Redirect after register oder login doesn't work with 'home' => '/profil' in fortify-config
I also activated the EmailVerification.
I'm using Laravel Fortify without Jetstream.

### Steps To Reproduce

When I make a registration or login its redirect me to / instead of /profil

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by kakojak** [comment]
So I think it is a bug in the Laravel Fortify package if you install it without Jetstream.

**Comment by NatachaH** [comment]
Did you find any solution about that ?

In my research I found that it use the default Laravel middleware "RedirectIfAuthenticated" inside the method "defaultRedirectUri". But the weird thing is that the default Uri are fixed and I'm not sure how to changed them...
