### ISSUE TITLE
How translate this string with inner parameters?

### ISSUE THREAD

**Issue by luisprmat** [laravel/fortify#54]
https://github.com/laravel/fortify/blob/13d18335759a0f4a67543e69596ee23b085dcb0e/src/Rules/Password.php#L76

Revieving this line (also [70](https://github.com/laravel/fortify/blob/13d18335759a0f4a67543e69596ee23b085dcb0e/src/Rules/Password.php#L70), [72](https://github.com/laravel/fortify/blob/13d18335759a0f4a67543e69596ee23b085dcb0e/src/Rules/Password.php#L72), [74](https://github.com/laravel/fortify/blob/13d18335759a0f4a67543e69596ee23b085dcb0e/src/Rules/Password.php#L74))

```
return __('The :attribute must be at least '.$this->length.' characters.');
```
it's very difficult translate with the param.  Isn't it easier to write it as

```
return __('The :attribute must be at least :value characters.', ['value' => $this->length]);
```
?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by SanderMuller** [comment]
I agree that a translation string of `The :attribute must be at least :value characters.` (or similar) makes more sense than `The :attribute must be at least '.$this->length.' characters.`, so the translation key stays the same when updating the password requirements.

**Comment by luisprmat** [comment]
I just wanted to ask the community if they agreed to formulate a PR by changing these lines to the one suggested to facilitate the translation process, as this is inherent to this component.
