### ISSUE TITLE
[Feature Request] Add WebAuthn

### ISSUE THREAD

**Issue by GunniBusch** [laravel/fortify#541]
Hi,
would it be possible to add WebAuthn? 
This would allow for an even better login experience.

**Comment by crynobone** [comment]
Duplicate of #22

**Comment by GunniBusch** [comment]
> Duplicate of #22

Yeah, but that was 4 years ago. Now Webauthn is becoming more common. And this would be a nice feature, since more and more people are using this.

**Comment by jhdxr** [comment]
Agreed. Now it's almost the end of 2025, and the nature of Webauthn is very different from 2020. Windows/iOS/android has built-in support for it for years, and all the popular websites are using passkeys to replace 2FA or even the whole login (username+password).
