### ISSUE TITLE
Custom RecoveryCode generator

### ISSUE THREAD

**Issue by tomwelch** [laravel/fortify#542]
Hi,

Recently I had the situation where we wanted to customise the format of the recovery codes generate by Fortify. As `RecoveryCode::generate()` is called statically I had to extend a couple of actions and the TwoFactorAuthenticatable trait and override some methods to be able to call my own RecoveryCode class.

I can make a PR to make this more configurable, but I was wondering people's thoughts on binding RecoveryCode to the container vs. having a `Fortify::generateRecoveryCodesUsing()` method that could be placed in a service container?

Cheers,
Tom.

**Comment by tomwelch** [comment]
Hi @crynobone,

The RecoveryCode class in Fortify generates codes with:

```php
Str::random(10).'-'.Str::random(10)
```

I needed to create codes that were shorter and all lowercase. For example:

```php
Str::lower(Str::random(6).'-'.Str::random(6))
```

What I'm proposing is to offer a way to make the Recovery Key generation customisable.

Cheers,
Tom.

**Comment by driesvints** [comment]
Thank you @tomwelch. I believe the correct path forward here is to send in a PR so Taylor can look at some actual code. Thanks
