### ISSUE TITLE
Cannot authenticate if the field "remember" is passed as false

### ISSUE THREAD

**Issue by joaoribeiro-controlink** [laravel/fortify#546]
### Fortify Version

1.21.3

### Laravel Version

11.11.0

### PHP Version

8.2.5

### Database Driver & Version

MySQL 8

### Description

Fortify does not make a successful authentication if the "remember" field is not passed as true.

### Steps To Reproduce

Adding this to the FortifyServiceProvider on the boot method: 

```
Fortify::authenticateUsing(function (Request $request) {
  if(Auth::attempt($request->only('username', 'password'), $request->filled('remember'))){
      // Regenerate the session to avoid session fixation
      $request->session()->regenerate();
  
      // Return the authenticated user instance
      return Auth::user();
  }
  
  return null;
});
```

**Comment by driesvints** [comment]
This should work. `$remember` is a boolean which when being `false` will just not remember the session.

**Comment by driesvints** [comment]
If you need help with this please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by joaoribeiro-controlink** [comment]
I found the problem, the User model cannot have the HasUuids Trait, if this is added to the model the login stop working
