### ISSUE TITLE
Use fortify authentication in multiple places of the same website

### ISSUE THREAD

**Issue by AjithLalps** [laravel/fortify#56]
Using `laravel/UI` we can create authentication scaffold on multiple places or for multiple users like `admin`, `normal users` by copy-pasting the same scaffold generated by the `--auth` flag. 

How can we achieve the same with `fortify`? 

How can we use forify to authorize `admin` and `normal users`?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by AjithLalps** [comment]
Hi @driesvints I know this issue will be closed, but I tried the forums and didn't receive any response from it and I didn't find any documentation on the internet.

**Comment by wandyyd** [comment]
Hi @AjithLalps - been wondering, have you get the answer of this?
I've been "walk around" on stackoverflow & laracast, but no one mentioned on there, or perhaps, my keyword doesn't hit when I lookup around.

What I'm trying to search is same like yours, but, I do add something "different tables". Since, I want to separate the table between Admin and (normal) User

Thanks! 😄

**Comment by AjithLalps** [comment]
Hi @wandyyd,

I didn't get the answer for this. I also tried all of your way and I didn't
get any aswer from anywhere. So I integrated the laravel ui package to
achieve the same.

**Comment by wandyyd** [comment]
I see. Thanks @AjithLalps for letting me know.
I guess, I will follow your path, to stick with laravel ui at the moment.

**Comment by AjithLalps** [comment]
I think it will be good for the moment.

**Comment by stsepelin** [comment]
Hey @wandyyd, @AjithLalps I've seen a video on [youtube](https://www.youtube.com/watch?v=iWbkL8q9bKM) with a solution to your problem. The source code from this video is placed [here](https://github.com/imranrbx/laravel-8-fortify-multi-auth-with-jetstream).

**Comment by wandyyd** [comment]
Thanks @stsepelin for your info. But unfortunately, I can't really understand that video, hopefully, in the future, there'll be another package/video about it.

By the way, @AjithLalps @stsepelin I found this summary [video](https://www.youtube.com/watch?v=L1FVdHdEm_8) - regarding L8 updates and community feedback.
And they said, they will continue to support Laravel UI 😄 🎉

If we plan to stay with Laravel UI, we can use that. Or if we want to, we can try and learn more around about Laravel Fortify.
Now, we're free to choose! And, let's keep to support Laravel community! 😄

**Comment by AjithLalps** [comment]
@stsepelin thanks for sharing the code. If you don't mind can you share the
video link?
@wandyyd yah. i saw taylors live streaming and the description update on
the laravel ui package.
