### ISSUE TITLE
Password reset requests don't respect lowercase_usernames setting

### ISSUE THREAD

**Issue by mattmcdonald-uk** [laravel/fortify#561]
### Fortify Version

1.23.0

### Laravel Version

11.20.0

### PHP Version

8.3.x

### Description

When setting `lowercase_usernames` to `true` attempts to request password reset links will use the case sensitive user input.

### Steps To Reproduce

Set `lowercase_usernames => true` in `config/fortify.php`

Register a user account with the email `test@example.org`

Request a password reset email with the email `TEST@example.org`

**Comment by driesvints** [comment]
You've sent a PR so let's see how it goes.
