### ISSUE TITLE
Passport-reset fails with custom routes Fortify::viewPrefix and fortify.redirects

### ISSUE THREAD

**Issue by Deracination** [laravel/fortify#566]
### Fortify Version

1.24.0

### Laravel Version

11.21.0

### PHP Version

8.3.10

### Description

vendor/laravel/fortify/src/Http/Responses/PasswordResetResponse.php always calls route('login') even when there is a Fortify::redirect defined for 'passport-reset'.

This means that passport resets always fail when using custom routes defined with Fortify::viewPrefix and config()->set('fortify.redirects.password-reset')

A work-around is to define a dummy /login route.

### Steps To Reproduce

1. Set a custom route prefix for fortify with Fortify::ignoreRoutes() and Fortify::viewPrefix
2. Provide a custom reset url with config()->set('fortify.redirects.password-reset','/my-reset-finish')
3. Run a user through the passport reset flow

**Comment by driesvints** [comment]
Thanks. Right now we don't plan on changing this. If you want, you can attempt a PR to provide a non breaking solution to this.
