### ISSUE TITLE
Undefined variable: request in reset-password.blade.php

### ISSUE THREAD

**Issue by BlogProgWEB** [laravel/fortify#57]
- Fortify Version: 8.4.0
- Laravel Version: 8.4.0
- PHP Version: 7.3.9
- Database Driver & Version: 5.7.x

### Description:

Undefined variable: request in `reset-password.blade.php` when I override view `forgot-password`

### Steps To Reproduce:

Clean installation Laravel Framework 8.4.0 without any auth scaffolding.

Db migration and seed - it's ok!

Then: 

`composer require laravel/fortify` 

and php artisan vendor:publish...

`php artisan migrate`

It's ok!

Created in `FortifyServiceProvider` in `boot()` :

```php
Fortify::requestPasswordResetLinkView(function () {  
  return view('admin.auth.forgot-password');  
});  
  
Fortify::resetPasswordView(function () {  
  return view('admin.auth.reset-password');  
});
```
And created views in `view/admin/auth` folder:
`forgot-password.blade.php`
```php
<form method="POST" action="/forgot-password">  
  @csrf  
  <input id="email" type="email" name="email" value="{{ old('email') }}" required>  
  <button type="submit">  
  {{ __('Send Password Reset Link') }}  
  </button>  
</form>
```
`reset-password.blade.php`
```php
<form method="POST" action="/reset-password">  
  @csrf  
  <input type="hidden" name="token" value="{{ $request->route('token') }}">  
</form>
```
Then in browser `/forgot-password` Send Password Reset Link

From mail go to link `/reset-password/543c9a...hash?email=admin%40example.com` 

I get 
~~~
ErrorException
Undefined variable: request (View: ...\resources\views\admin\auth\reset-password.blade.php)`
~~~

It also doesn't work if I am using `Jetstream` and want to override the view `forgot-password` in `JetstreamServiceProvider` in `boot()` and sets any folder. 

Even if I only specify this, I will not change anything else from a clean install (liveware).
```php
Fortify::requestPasswordResetLinkView(static function () {
    return view('auth.forgot-password');
});
```

**Comment by BlogProgWEB** [comment]
Maybe this is not a wrong, and I didn't read something in the documentation or did I do it wrong?

**Comment by driesvints** [comment]
Docs are missing this: 

```
Fortify::resetPasswordView(function ($request) {  
  return view('admin.auth.reset-password', ['request' => $request]);  
});
```

I'll send in a PR. Thanks.
