### ISSUE TITLE
Cant reset password with config views = false

### ISSUE THREAD

**Issue by projct1** [laravel/fortify#581]
### Fortify Version

1.25.0

### Laravel Version

11.34.2

### PHP Version

8.3.10

### Database Driver & Version

MySQL 8.0

### Description

I am using laravel only as api.
For ui i using nuxtjs.
Login and register routs are works fine.
But when i trying to send POST-request `/forgot-password`, i got error `Route [password.reset] not defined.`
But if i change `views => true`, all is ok, email is sending with response:
```json
{
    "message": "We have emailed your password reset link."
}
```

### Steps To Reproduce

Fresh install Laravel + Fortify.

Here is my `fortify.php`:
```php
return [
    'guard' => 'web',

    'passwords' => 'users',

    'username' => 'email',

    'email' => 'email',

    'limiters' => [
        'login' => 'login',
        'two-factor' => 'two-factor',
    ],

    'views' => false,

    'features' => [
        Features::registration(),
        Features::emailVerification(),
        Features::resetPasswords()
    ]
];
```
Here is my `FortifyServiceProvider.php`:
```php
class FortifyServiceProvider extends ServiceProvider
{
    public function boot(): void
    {
        Fortify::createUsersUsing(CreateNewUser::class);
    }
}
```
Here is my route list:
![image](https://github.com/user-attachments/assets/d4bbdd5b-70f1-4b41-87e0-ff469e39ca3d)

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
