### ISSUE TITLE
Customizing Logout

### ISSUE THREAD

**Issue by Behzadassadi** [laravel/fortify#62]
It would be handy if there was a way to customize the logout function .!
so if we have multiple guard then we can limit the function to log out the user only not the admins.

**Comment by ali-alharthi** [comment]
Fortify has the following in its config file: `'guard' => 'web'`.
I am sure it only uses that guard for everything it does including the logout 👍🏼 
This is what Fortify does in the `destroy` method a.k.a logout: `$this->guard->logout();` (and other stuff session too!).

BTW, Laravel as a whole is built in OOP so you can simply extend any class from its core or any package to implement additional logic (code) for your case.

I believe @taylorotwell built Fortify to be the official Laravel package for authentication. However, consider it as a skeleton, so you can implement your logic using the way I mentioned above.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by digenPrime** [comment]
I want to add an activity and save that activity in database such that "@username has logged out at H:i:s". Can someone tell me how to do this? @driesvints  @ali-alharthi.

**Comment by ChaudharyHabib** [comment]
this issue should be open. how to overwrite the method mentioned by @ali-alharthi

**Comment by ali-alharthi** [comment]
@digenPrime You should read more about events. It should direct you to the correct way.
@ChaudharyHabib This isn't an issue as explained by @driesvints 
Nevertheless, you can overwrite it by simply, use a custom routes and use you custom controller that extends Fortify's controller or simply build yours. I wouldn't go into deep but here is a key thing: `Fortify::ignoreRoutes();`.

**Comment by cartayapardo** [comment]
Hello, I am using fortify and it happens that when I logout and try to login with another user, I access with the previous user and not with the new one. This does not always happen, what can be wrong?
