### ISSUE TITLE
Target [Laravel\Fortify\Contracts\CreatesNewUsers] is not instantiable.

### ISSUE THREAD

**Issue by jozeflambrecht** [laravel/fortify#7]
- Fortify Version: 0.0.1
- Laravel Version: 8.x-dev 02522b0
- PHP Version: 7.3.21
- Database Version: 8.0.19
### Description:

Illuminate\Contracts\Container\BindingResolutionException
Target [Laravel\Fortify\Contracts\CreatesNewUsers] is not instantiable.

### Steps To Reproduce:
Windows environment

`laravel new jetstream --jet --dev`
select livewire and teams
`php artisan migrate`
`php artisan serve`

Register a new user and click "Register"

**Comment by zaknesler** [comment]
Make sure that you are registering the service providers in `config/app.php`:

```php
App\Providers\FortifyServiceProvider::class,
App\Providers\JetstreamServiceProvider::class, // If using Jetstream
```

**Comment by jozeflambrecht** [comment]
Thanks @zaknesler

**Comment by deadstar1** [comment]
> Make sure that you are registering the service providers in `config/app.php`:
> 
> ```
> App\Providers\FortifyServiceProvider::class,
> App\Providers\JetstreamServiceProvider::class, // If using Jetstream
> ```

does not work on me 
![image](https://user-images.githubusercontent.com/6646675/94651511-2427d780-032b-11eb-902d-a5c8ac6580c7.png)

**Comment by NoOorZ24** [comment]
> > Make sure that you are registering the service providers in `config/app.php`:
> > ```
> > App\Providers\FortifyServiceProvider::class,
> > App\Providers\JetstreamServiceProvider::class, // If using Jetstream
> > ```
> 
> does not work on me

https://github.com/laravel/fortify#authentication

**Comment by kystudio-jerry** [comment]
> > Make sure that you are registering the service providers in `config/app.php`:
> > ```
> > App\Providers\FortifyServiceProvider::class,
> > App\Providers\JetstreamServiceProvider::class, // If using Jetstream
> > ```
> 
> does not work on me
> ![image](https://user-images.githubusercontent.com/6646675/94651511-2427d780-032b-11eb-902d-a5c8ac6580c7.png)

you just need use one of list in your config/app.php depend on your solution by fortify or jetstream.

**Comment by Said20hr** [comment]
You have to add 
App\Providers\FortifyServiceProvider::class,
then don't forget to clear the cache

**Comment by risurina** [comment]
As per docs https://laravel.com/docs/8.x/fortify#registration.
You should add `Fortify::registerView(fn () => view('auth.register'));` in `FortifyServiceProvider.php`

**Comment by semul** [comment]
`php artisan config:clear` can solve this issue.

**Comment by shortdark** [comment]
The Fortify docs give you this for /login...

```Fortify::loginView(fn () => view('auth.login'));```

But, for /register you would also need this...

```Fortify::registerView(fn () => view('auth.register'));```

Not having this will cause the error...

> Target [Laravel\Fortify\Contracts\RegisterViewResponse] is not instantiable

**Comment by seguce92** [comment]
> > Make sure that you are registering the service providers in `config/app.php`:
> > ```
> > App\Providers\FortifyServiceProvider::class,
> > App\Providers\JetstreamServiceProvider::class, // If using Jetstream
> > ```
> 
> does not work on me
> ![image](https://user-images.githubusercontent.com/6646675/94651511-2427d780-032b-11eb-902d-a5c8ac6580c7.png)

Verify that the following providers are registered in the `config.app` file in the `providers` section

```php
App\Providers\FortifyServiceProvider::class,
App\Providers\JetstreamServiceProvider::class, // If using Jetstream
```

Uncomment the following line in the `App\Providers\FortifyServiceProvider.php` file

```php
Fortify::createUsersUsing(CreateNewUser::class);
```

**Comment by wandumi** [comment]
@seguce92 did you manage to solve the problem?

**Comment by seguce92** [comment]
> @seguce92 did you manage to solve the problem?
> 

Yes, do the above steps and everything worked correctly.

**Comment by wandumi** [comment]
@seguce92 I think lots of peoples solution it halfway, I am seeing it will require me to create the views to finalize the whole process right? I just installed and because I saw the login URL I thought it will work as laravel/UI was doing.

**Comment by kishanterry** [comment]
Landed here after installing Jetstream, if none of the above solution works, check the `./bootstrap/providers.php`. It should look like:
```
<?php

return [
    App\Providers\AppServiceProvider::class,
    App\Providers\FortifyServiceProvider::class,
    App\Providers\JetstreamServiceProvider::class,
];
```
The return array was missing `App\Providers\FortifyServiceProvider::class,` for me ... somehow the automagic missed it.

Cheers!

**Comment by shimanta-png** [comment]
> App\Providers\AppServiceProvider::class,
>     App\Providers\FortifyServiceProvider::class,

Thanks! after your suggestion my problem solved!
inside bootstrap\providers.php
return [
    // add the below line 
     App\Providers\FortifyServiceProvider::class,
    AppServiceProvider::class,
];
