### ISSUE TITLE
Customize Password.php messages

### ISSUE THREAD

**Issue by jmpagella** [laravel/fortify#73]
Recently i see the PR https://github.com/laravel/fortify/pull/70 to get a better way to translate those strings and I really appreciate that, but what if a want to custom that messages? Maybe a way to achieve that is with lang files or a possibility to change it in ValidationRules action published.

**Comment by leo95batista** [comment]
Please, see mi PR #79 . Regards

**Comment by jmpagella** [comment]
I just saw the PR and I think it is a good way to modify the text of those messages. I think Taylor thought it was just to translate and how he said, that function was applied in the PR that I mentioned earlier. Thanks anyway.
Please let me know if i close this issue

**Comment by driesvints** [comment]
Closing because related PR was closed.
