### ISSUE TITLE
Redirection customization

### ISSUE THREAD

**Issue by webchopin** [laravel/fortify#77]
It would be nice to offer customization options for redirection such as `Fortify::redirectAfterLoginUsing($callback)` or `Fortify::redirectAfterRegisterUsing($callback)`. This would bring back `laravel/ui` `redirectTo` capabilities. What do you think ? Do you prefer to encourage people to use custom Response classes and to put them under `app/Http/Responses/Fortify` ?

Concerning the registration use case, maybe it's pretty common to redirect users to a tour/guide page, so what do you think about a dedicated configuration key to set the path ?

**Comment by rafayrty** [comment]
Hi There Add This To The Route File It Should Work.
```
Route::get('/login',function(){
    return redirect()->route('index');
})->name('login');
```

**Comment by Adhik13th** [comment]
i think its not like that

**Comment by nadhifikbarw** [comment]
Here's a workaround that if you need to implement it right now. I would absolutely prefer much more cleaner solution but for now this will do

---
Add new config key in `config/fortify.php`
```php
'registered' => '/onboarding',
```
or you could also make it use `RouteServiceProvider` const
```php
// app/providers/RouteServiceProvider.php
public const REGISTERED_REDIRECT = '/onboarding'


// app/config/fortify.php
'registered' => App\Provider\RouteServiceProvider::REGISTERED_REDIRECT,
```

Create new class `App\Responses\RegisterResponse`
```php
<?php

namespace App\Responses;

use Illuminate\Http\Response;
use Laravel\Fortify\Contracts\RegisterResponse as RegisterResponseContract;

class RegisterResponse implements RegisterResponseContract
{
    public function toResponse($request)
    {
        return $request->wantsJson()
            ? new Response('', 201)
            : redirect(config('fortify.registered'));
    }
}
```


Bind new interface implementation inside `FortifyServiceProvider.php`
```php
use App\Responses\RegisterResponse;
use Laravel\Fortify\Contracts\RegisterResponse as RegisterResponseContract;

/**
* Register any application services.
*
* @return void
*/
public function register()
{
    $this->app->bind(
        RegisterResponseContract::class,
        RegisterResponse::class
    );
}
```

**Comment by jonasvanderhaegen** [comment]
Using Laravel v8.9.0, On top of RouteServiceProvider:

    /**
     * The path to the "home" route for your application.
     *
     * This is used by Laravel authentication to redirect users after login.
     *
     * @var string
     */
    public const HOME = '/';

**Comment by joshmorel** [comment]
@jonasvanderhaegen this is okay for certain use cases. But imagine I wanted to customize further, e.g. redirect to a variable path after profile update (imagine -> profile/MyNewUserName)

**Comment by mrpritchett** [comment]
+1 for this feature request

**Comment by taylorotwell** [comment]
Feel free to send a PR.

**Comment by c0nst4ntin** [comment]
I'm not too familiar with this, but couldn't publishing single response classes and then having the possibility to overwrite these work? If so, is there a way?

**Comment by sambindoff** [comment]
@c0nst4ntin that's exactly what @nadhifikbarw's [suggestion](https://github.com/laravel/fortify/issues/77#issuecomment-701889858) above accomplishes, simply create a response class and bind this to the container as the Fortify register response.

**Comment by betopicapiedra** [comment]
**Hello, I would like to know how I can do to customize the redirection after logging out.
I see that by default it redirects you to the index of your project, I don't like that .. please help**

**Comment by nadhifikbarw** [comment]
@betopicapiedra You could use the same method like my previous suggestion, but instead of rebinding the `RegisterResponse` contract, rebind the `LogoutResponse` contract instead.

**Comment by betopicapiedra** [comment]
I already did what you suggested but it doesn't work
@nadhifikbarw

**Comment by betopicapiedra** [comment]
![laravel](https://user-images.githubusercontent.com/5233084/103447168-32003800-4c4d-11eb-8c4b-64dd5a9ebb16.png)

**Comment by betopicapiedra** [comment]
Ya lo solucione ....
en el archivo RouteServiceProvider.php escribi esta linea
----------------------------------------------------------------------------------
![Captura de pantalla (12)](https://user-images.githubusercontent.com/5233084/103448082-c6709780-4c59-11eb-8a58-82cd612069a6.png)

public const LOGOUT_REDIRECT = '/login'; <------  que redirecciona al login 
-------------------------------------------------------------------------------
luego en el archivo fortify.php la mande a llamar con el nombre 'salir'
---------------------------------------------------------------------------------
![Captura de pantalla (14)](https://user-images.githubusercontent.com/5233084/103448161-20259180-4c5b-11eb-80d6-dc6d99381f5a.png)
--------------------------------------------------------------------------------
luego cree una carpeta llamada Responses dentro de la carpeta app. Ahí cree un archivo llamado LogoutResponse.php y en ese archivo mande a llamar a la constante (no me queda claro si es constante o variable) con el nombre salir
-------------------------------------------------------------------------------------------------------------------------
![Captura de pantalla (17)](https://user-images.githubusercontent.com/5233084/103448283-fe2d0e80-4c5c-11eb-8e2b-d04e352ddfa1.png)

**Comment by victoralbino** [comment]
In the pull request  implemented the possibility to perform some action after the user registers
Now it is only necessary to implement the afterRegister() method in the App\Actions\Fortify\CreatesNewUsers Class and what is in it will be executed after registration.

**Comment by nadhifikbarw** [comment]
@betopicapiedra Please use English so it's easier for everyone, but assuming from your screenshot, you haven't bind your `LogoutResponse` implementation with `LogoutResponseContract` via `FortifyServiceProvider`

**Comment by betopicapiedra** [comment]
**_Ya esta solucionado ....gracias ..._**

**Comment by Doukuest** [comment]
+1

**Comment by jimgwhit** [comment]
Custom redirection has been handled, see https://laracasts.com/discuss/channels/laravel/version-8-redirects

**Comment by nekooee** [comment]
> Here's a simple workaround if you need to implement it right now. However I would too absolutely prefer much more cleaner solution, such as adding new dedicated config key would be the easiest implementation, but for now this should do.
> 
> Add new config key in `config/fortify.php`
> 
> ```
> 'registered' => '/onboarding',
> ```
> 
> or you could also make it use `RouteServiceProvider` const
> 
> ```
> // app/providers/RouteServiceProvider.php
> public const REGISTERED_REDIRECT = '/onboarding'
> 
> 
> // app/config/fortify.php
> 'registered' => App\Provider\RouteServiceProvider::REGISTERED_REDIRECT,
> ```
> 
> Create new class `App\Responses\RegisterResponse`
> 
> ```
> <?php
> 
> namespace App\Responses;
> 
> use Illuminate\Http\Response;
> use Laravel\Fortify\Contracts\RegisterResponse as RegisterResponseContract;
> 
> class RegisterResponse implements RegisterResponseContract
> {
>     public function toResponse($request)
>     {
>         return $request->wantsJson()
>             ? new Response('', 201)
>             : redirect(config('fortify.registered'));
>     }
> }
> ```
> 
> Bind new interface implementation inside `FortifyServiceProvider.php`
> 
> ```
> use App\Responses\RegisterResponse;
> use Laravel\Fortify\Contracts\RegisterResponse as RegisterResponseContract;
> 
> /**
> * Register any application services.
> *
> * @return void
> */
> public function register()
> {
>     $this->app->bind(
>         RegisterResponseContract::class,
>         RegisterResponse::class
>     );
> }
> ```

If the user is already logged in and goes to /login URL this will not work and they will be redirected to the same default path again. How can this problem be solved?

**Comment by gaborszita** [comment]
+1
