### ISSUE TITLE
BindingResolutionException

### ISSUE THREAD

**Issue by MrMarlow** [laravel/fortify#81]
- Fortify Version: 1.5.0
- Laravel Version: 8.6.0
- PHP Version: 7.4.8
- Database Driver & Version: MySQL 5.7

### Description:

Upon installing Laravel/Fortify on a clean install, you receive errors on the login and register endpoints.

Errors, respectively;

    Target [Laravel\Fortify\Contracts\LoginViewResponse] is not instantiable.

and

    Target [Laravel\Fortify\Contracts\RegisterViewResponse] is not instantiable.

### Steps To Reproduce:

    laravel new project
    cd project
    composer require laravel/fortify
    php artisan vendor:publish --provider="Laravel\Fortify\FortifyServiceProvider"
    php artisan migrate

**Comment by driesvints** [comment]
https://github.com/laravel/fortify/tree/master#authentication

> To get started, we need to instruct Fortify how to return our login view. Remember, Fortify is a headless authentication library. If you would like a frontend implementation of Fortify that is already completed for you, you should use Laravel Jetstream.

**Comment by devingray** [comment]
Anyone else coming here for this. 

https://github.com/laravel/fortify/issues/7
