### ISSUE TITLE
customize controllers and requests

### ISSUE THREAD

**Issue by bidbprojects** [laravel/fortify#82]
Hello there. I want to customize the controls and requests, but I cannot do the customizations in the vendor because requests and controls files are not sent in shared files.
![Ekran Alıntısı](https://user-images.githubusercontent.com/71431859/94006070-f204fb80-fda7-11ea-995d-a7ca49994871.PNG)

**Comment by bidbprojects** [comment]
I want I can interfere with the verification rules

**Comment by driesvints** [comment]
Overwrite the route and controller method with a custom request object.
