### ISSUE TITLE
[1.x] Route Confirm Password remains active even when I disable all features

### ISSUE THREAD

**Issue by leo95batista** [laravel/fortify#84]
- Fortify Version: 1.5.0
- Laravel Version: 8.6.0
- PHP Version: 7.4.7
- Database Driver & Version:

### Description:
When I disable all the features within the ```fortify.php``` configuration file

```
    'features' => [
        //
    ],
```

the default Fortify routes are disabled, but the ```password confirmation route``` is still enabled. Is this a bug, or is it intentionally defined that way?

![imagen](https://user-images.githubusercontent.com/70990619/94025017-0e903c00-fd86-11ea-8831-af02f8aaf509.png)

### Steps To Reproduce:

1. Run ``` laraven new app ```
2. Run ``` composer require laravel/fortify ```
3. Run ``` php artisan vendor:publish --provider="Laravel\Fortify\FortifyServiceProvider" ```
4. Go to ``` config/fortify.php ``` and remove all keys within ``` features ``` array
5. Run ``` php artisan route:list ```

**Routes:**

[GET|HEAD|POST]
``` user/confirm-password ``` 

[GET|HEAD]
``` user/confirmed-password-status ```

I think there should be a conditional that groups these routes in the ```routes.php``` file.

https://github.com/laravel/fortify/blob/77bd46ac1729939a8db97b890a4d752dce79dc53/routes/routes.php#L95-L104

**Comment by DarthShmev** [comment]
Make sure you've cached your config and routes after making those changes. 

`php artisan config:cache`
Then:
`php artisan route:cache`

**Comment by driesvints** [comment]
Sounds like a feature request. Feel free to PR something 👍
