### ISSUE TITLE
Sent Verification Message not formatted

### ISSUE THREAD

**Issue by jasminetracey** [laravel/fortify#88]
- Fortify Version: 1.4.3
- Laravel Version: 8.5.0
- PHP Version: 7.4
- Database Driver & Version:

### Description:
Verification status message is incorrect

### Steps To Reproduce:
Request email verification to be sent 

```php
return $request->wantsJson()
                    ? new Response('', 202)
                    : back()->with('status', 'verification-link-sent');
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by jasminetracey** [comment]
@driesvints This is a bug it has to do with the code itself. the function returns the message `verification-link-sent` as the status when a verification email is sent
