### ISSUE TITLE
Enhance routing with config options

### ISSUE THREAD

**Issue by MarkIvanowich** [laravel/fortify#9]
I like to place my login endpoints behind a prefixed path. (& honeypot common endpoints :wink: )

I'm surprised to see that both Fortify and Jetstream boot their routes inside `src/FortifyServiceProvider`, instead of from a user's route declaration like how `Auth::routes()` worked.

https://github.com/laravel/fortify/blob/65c695ddcbc29efc1b985fb6a4932daa5c9e80a2/src/FortifyServiceProvider.php#L110-L118

Perhaps merging the existing group options with an array found in `config/fortify.php`?

```php
    'route_options' => [
        'prefix' => 'secret', // This makes the login page /secret/login
        /* 'domain' => null, */
    ],
```

**Comment by MarkIvanowich** [comment]
If the user does enable a prefix, then all the current view paths / links will break. 

We could leave this as the user's responsibility to publish and edit. Or we could replace the current static paths with route names:
```blade
        {{--<form method="POST" action="/login">--}}
        <form method="POST" action="{{route('login')}}">
            @csrf
            ...
```

**Comment by undjike** [comment]
I'm facing a similar problem. I want to populate Fortify Routes in a route group to enable route globalization. For instance...

```php
Route::localized(function () {
     // Fortify Routes here
});
```

**Comment by thecodemill** [comment]
Still experimenting, but what I've done is:

**app/Providers/FortifyServiceProvider.php**
```
public function register()
{
    Fortify::ignoreRoutes();
}
```

**routes/web.php**
```
Route::prefix('auth')->group(function () {
    require base_path('vendor/laravel/fortify/routes/routes.php');
});
```

Or you could redefine the routes entirely instead of requiring them.

**Comment by c0nst4ntin** [comment]
@thecodemill have you continued this approach or found a different way?

**Comment by paras-malhotra** [comment]
See https://github.com/laravel/jetstream/pull/67
