### ISSUE TITLE
Home Path not working correctly

### ISSUE THREAD

**Issue by alturic** [laravel/fortify#92]
- Fortify Version: 1.5.0
- Laravel Version: 8.6.0
- PHP Version: 7.3

### Description:

I'm unsure if this is a Fortify issue or a Laravel issue or even me not using middleware correct, however in my config/fortify.php I have `'home' => RouteServiceProvider::HOME,` and in my `RouteServiceProvider` I have `public const HOME = '/home';` yet when I try logging in I get sent to my /not-subscribed route. If I comment out my / route, I get sent to /home. If I put `Route::view('/home', 'home');` above the / route I get sent to /home.

My route looks like the following, and yes I do want every route to have an authenticated user.

```
Route::middleware(['auth'])->group(
    function () {
        Route::middleware([MyCustomMiddleware::class])->group(
            function () {
                Route::get(
                    '/',
                    function () {
                        return view('welcome');
                    }
                );
            }
        );
        Route::view('/home', 'home');
        
        Route::get('/not-subscribed', NotSubscribedIndexAction::class)->name('auth.notsubscribed');
    }
);
```

As you might have seen, my / route does have a middleware on it, which is why I get redirected to /not-subscribed upon login when having my routes in that order.

I also did a test where I strictly had the following and it *does* work correctly, so again, I'm unsure if this is a Fortify issue, Laravel issue, or me not using middleware correctly.

```
        Route::get(
            '/',
            function () {
                return view('welcome');
            }
        );
        Route::view('/home', 'home');
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
