### ISSUE TITLE
Modify error message logic

### ISSUE THREAD

**Issue by JamesZXCVBNM** [laravel/fortify#94]
I'm trying to rebuild a specific authentication implementation we were using in Laravel 7 with Fortify, however, there doesn't seem to be a way to modify the authorisation error message returned to the user within the `Fortify::authenticateUsing()` method.

For example:

```php
$user = User::where('username', $request->username)->first();

if ($user && in_array($user->status_id, [1,2,3])) {
    if (Hash::check($request->password, $user->password)) {
        return $user;
    }
}
else {
    // custom error message here -- doesn't work
    $request->session()->flash('errors', 'Account does not exist or is inactive. Check your username.');
}
```

I've traced this back to the `Laravel/Fortify/Actions/AttemptToAuthenticate` class and the `throwFailedAuthenicationException` function which allows you to customise the message via the `resources\lang\en\auth.php` file, but there doesn't seem to be a way of modifying the logic of which message should be returned anywhere?

If I'm wrong, could the documentation be updated to show how?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by JamesZXCVBNM** [comment]
> there doesn't seem to be a way of modifying the logic of which message should be returned anywhere?

It'd be cool to get an answer? If there is a way, that's fine, I'll go seek help on StackOverflow

**Comment by JamesZXCVBNM** [comment]
If there was a customisable action e.g:

`Fortify::attemptToAuthenticateUsing(); `

that we could use in the same way as the other Actions, this would solve the problem, I think.

Again, @driesvints, this is a Feature Request

**Comment by driesvints** [comment]
@JamesZXCVBNM if you want to change anything feel free to send in a pr

**Comment by JamesZXCVBNM** [comment]
For anyone else who stumbles on the same problem. This might help:

```php
if ($user && in_array($user->status_id, [1,2,3])) {
    if (Hash::check($request->password, $user->password)) {
        return $user;
    }
}
else {
    throw ValidationException::withMessages([
        Fortify::username() => "Username not found or account is inactive. Please check your username.",
    ]);
}
```

It'd be great if the documentation could be updated to include something like that as an example

**Comment by driesvints** [comment]
@JamesZXCVBNM if you want to add something feel free to PR it 👍
