### ISSUE TITLE
Option to remember 2FA code for x days

### ISSUE THREAD

**Issue by Chrissi2812** [laravel/fortify#95]
Would be nice to have an option to remember the 2fa code for e.g 7 days for a device.

Plesk for example is doing something similar (the days are configurable in this case): 
![image](https://user-images.githubusercontent.com/6141652/94443456-7ccd6800-01a5-11eb-915e-d65c561d46e6.png)

**Comment by driesvints** [comment]
Closing this as the PR for this was rejected.
